"use strict";
/* =====================================================================
   AYUDA CONTEXTUAL / CONTEXT HELP  (signos «?» con concepto y escala)
   c = concepto; s = escala de decisión [nivel, texto]; niveles ok · warn · bad · info
   ===================================================================== */
const E = (es,en)=>({es,en});
const AYUDA = {
  /* ---------- nutrientes / nutrients ---------- */
  NEm:{c:E('Energía neta de mantenimiento: la energía de la dieta que el animal usa para vivir sin ganar ni perder peso (respirar, digerir, regular la temperatura). Se expresa en Mcal por kg de materia seca.','Net energy for maintenance: the dietary energy the animal uses to live without gaining or losing weight (breathing, digesting, keeping warm). Expressed in Mcal per kg of dry matter.'),
    s:[['info',E('Vacas con forraje: 1.1–1.4 Mcal/kg.','Cows on forage: 1.1–1.4 Mcal/kg.')],['info',E('Desarrollo: 1.5–1.8 Mcal/kg.','Growing: 1.5–1.8 Mcal/kg.')],['ok',E('Engorda con grano: 1.95–2.25 Mcal/kg.','Grain finishing: 1.95–2.25 Mcal/kg.')],['warn',E('Más de 2.25 con poco forraje: alto riesgo de acidosis.','Above 2.25 with little forage: high acidosis risk.')]]},
  NEg:{c:E('Energía neta de ganancia: la energía de la dieta que se convierte en tejido nuevo (músculo y grasa) después de cubrir el mantenimiento. Es la que fija cuántos kilos gana el animal.','Net energy for gain: the dietary energy turned into new tissue (muscle and fat) once maintenance is covered. It sets how many kilos the animal gains.'),
    s:[['info',E('Desarrollo: 0.9–1.15 Mcal/kg.','Growing: 0.9–1.15 Mcal/kg.')],['ok',E('Finalización: 1.30–1.55 Mcal/kg.','Finishing: 1.30–1.55 Mcal/kg.')],['warn',E('Si la ENg requerida sube de 1.6, la ganancia objetivo es muy alta para ese peso y consumo.','If required NEg exceeds 1.6, the target gain is too high for that weight and intake.')]]},
  TND:{c:E('Nutrientes digestibles totales: suma de proteína, carbohidratos y 2.25 veces la grasa digestibles. Es la medida clásica de energía; de ella se estima la energía metabolizable y la síntesis de proteína microbiana.','Total digestible nutrients: digestible protein plus carbohydrates plus 2.25 times digestible fat. The classic energy measure; metabolizable energy and microbial protein synthesis are estimated from it.'),
    s:[['info',E('Forrajes 50–65 %; granos 84–93 %.','Forages 50–65 %; grains 84–93 %.')],['ok',E('Finalización 78–85 %.','Finishing 78–85 %.')]]},
  PC:{c:E('Proteína cruda = nitrógeno × 6.25. En rumiantes es solo un indicador: lo que cuenta es cuánta proteína degradan los microbios (PDR) y cuánta llega al intestino (proteína metabolizable).','Crude protein = nitrogen × 6.25. In ruminants it is only an indicator: what matters is how much the microbes degrade (RDP) and how much reaches the intestine (metabolizable protein).'),
    s:[['ok',E('Finalización 12–14 %; desarrollo 13–16 %; vacas 8–12 %.','Finishing 12–14 %; growing 13–16 %; cows 8–12 %.')],['warn',E('Más de 15 % en engorda: nitrógeno desperdiciado y contaminación.','Above 15 % in finishing: wasted nitrogen and pollution.')]]},
  PM:{c:E('Proteína metabolizable: la proteína verdadera que se absorbe en el intestino. Viene de los microbios del rumen (64 % de la proteína microbiana) y de la proteína que escapa a la degradación (80 % de la PNDR). Es la que cubre los requerimientos de mantenimiento, crecimiento, gestación y leche.','Metabolizable protein: the true protein absorbed in the intestine. It comes from rumen microbes (64 % of microbial protein) and from protein escaping degradation (80 % of RUP). It covers maintenance, growth, pregnancy and milk.'),
    s:[['ok',E('Cubrir 100–110 % del requerimiento diario.','Cover 100–110 % of the daily requirement.')],['bad',E('Bajo el mínimo: la ganancia queda limitada por proteína.','Below minimum: gain is limited by protein.')],['info',E('En becerros ligeros suele ser el primer limitante; en finalización casi nunca.','Often first-limiting in light calves; rarely in finishing.')]]},
  PDRb:{c:E('Balance de proteína degradable: la PDR de la dieta menos la que necesitan los microbios para crecer con la energía disponible (proteína cruda microbiana, PCM = 42.73 + 0.087 × TND consumido, g/d). Si es negativo, los microbios no tienen suficiente nitrógeno y la dieta rinde menos.','Degradable protein balance: dietary RDP minus what the microbes need to grow on the available energy (microbial crude protein, MCP = 42.73 + 0.087 × TDN intake, g/d). If negative, microbes lack nitrogen and the diet underperforms.'),
    s:[['ok',E('0 o ligeramente positivo.','0 or slightly positive.')],['bad',E('Negativo: agrega urea o una proteína degradable.','Negative: add urea or a degradable protein.')],['warn',E('Muy positivo (> 20 g/kg): nitrógeno que se pierde por la orina.','Very positive (> 20 g/kg): nitrogen lost in urine.')]]},
  PDR:{c:E('Proteína degradable en rumen: la parte de la proteína que los microbios desdoblan a amoniaco y péptidos para construir su propia proteína.','Rumen-degradable protein: the share of protein the microbes break down into ammonia and peptides to build their own protein.'),
    s:[['info',E('Suele ser 60–70 % de la proteína cruda en dietas de engorda.','Usually 60–70 % of crude protein in feedlot diets.')]]},
  FDN:{c:E('Fibra detergente neutro: las paredes celulares (hemicelulosa, celulosa y lignina). Llena el rumen, limita el consumo y estimula la rumia.','Neutral detergent fiber: the cell walls (hemicellulose, cellulose, lignin). Fills the rumen, limits intake and stimulates rumination.'),
    s:[['ok',E('Finalización 12–20 %; desarrollo 25–40 %; vacas 40–60 %.','Finishing 12–20 %; growing 25–40 %; cows 40–60 %.')],['warn',E('Más de 55 %: el consumo cae por llenado.','Above 55 %: intake drops by rumen fill.')]]},
  FDNef:{c:E('FDN físicamente efectiva: la fibra larga que hace rumiar al animal y producir saliva, el amortiguador natural del rumen. Es FDN × factor de efectividad del tamaño de partícula.','Physically effective NDF: the long fiber that makes the animal ruminate and produce saliva, the rumen’s natural buffer. It is NDF × the particle-size effectiveness factor.'),
    s:[['bad',E('Menos de 6 % en engorda: pH ruminal bajo, acidosis, timpanismo y abscesos hepáticos.','Below 6 % in finishing: low rumen pH, acidosis, bloat and liver abscesses.')],['ok',E('7–10 % en finalización; 12–20 % en desarrollo; ≥ 20 % en vacas.','7–10 % in finishing; 12–20 % in growing; ≥ 20 % in cows.')]]},
  For:{c:E('Porcentaje de forraje (henos, rastrojos, ensilajes y pastos) en la materia seca de la dieta.','Percentage of forage (hays, stovers, silages and grasses) in the diet dry matter.'),
    s:[['ok',E('Finalización 8–15 %; recepción 30–45 %; desarrollo 35–60 %.','Finishing 8–15 %; receiving 30–45 %; growing 35–60 %.')],['warn',E('Menos de 8 %: solo con excelente manejo del comedero.','Below 8 %: only with excellent bunk management.')]]},
  EE:{c:E('Extracto etéreo: la grasa de la dieta. Aporta mucha energía, pero en exceso cubre la fibra y daña a los microbios que la digieren.','Ether extract: dietary fat. Supplies plenty of energy, but in excess it coats fiber and harms the microbes that digest it.'),
    s:[['ok',E('3–6 %.','3–6 %.')],['warn',E('Más de 6.5–7 %: baja la digestión de la fibra y el consumo.','Above 6.5–7 %: fiber digestion and intake drop.')]]},
  Ca:{c:E('Calcio: hueso, contracción muscular y leche. El requerimiento se calcula de forma factorial: mantenimiento + crecimiento + gestación + leche, con 50 % de absorción.','Calcium: bone, muscle contraction and milk. The requirement is factorial: maintenance + growth + pregnancy + milk, with 50 % absorption.'),
    s:[['ok',E('Engorda 0.5–0.8 %; vacas 0.2–0.4 %.','Feedlot 0.5–0.8 %; cows 0.2–0.4 %.')],['warn',E('Dietas de grano son pobres en Ca: siempre lleva carbonato.','Grain diets are low in Ca: always add limestone.')]]},
  P:{c:E('Fósforo: hueso, energía celular (ATP) y fertilidad. Se absorbe ≈ 68 %. Los granos y subproductos traen de sobra; en pastoreo suele faltar.','Phosphorus: bone, cell energy (ATP) and fertility. ≈ 68 % absorbed. Grains and by-products supply plenty; on pasture it is often short.'),
    s:[['ok',E('0.20–0.35 % según la etapa.','0.20–0.35 % depending on the stage.')],['warn',E('Exceso: caro y contamina (fósforo en excretas).','Excess: costly and polluting (phosphorus in manure).')]]},
  S:{c:E('Azufre: lo usan los microbios para formar aminoácidos azufrados. En exceso produce ácido sulfhídrico en el rumen y polioencefalomalacia. Ojo con DDGS, melaza y agua con sulfatos.','Sulfur: microbes use it to make sulfur amino acids. In excess it forms hydrogen sulfide in the rumen and causes polioencephalomalacia. Watch DDGS, molasses and sulfate-rich water.'),
    s:[['ok',E('0.15–0.25 %.','0.15–0.25 %.')],['bad',E('Más de 0.30 % en dietas altas en grano (0.40 % con más de 40 % de forraje).','Above 0.30 % in high-grain diets (0.40 % with over 40 % forage).')]]},
  Na:{c:E('Sodio: regula el agua del cuerpo y el apetito. Casi solo lo aporta la sal o el bicarbonato.','Sodium: regulates body water and appetite. Supplied almost only by salt or bicarbonate.'),
    s:[['ok',E('0.06–0.10 % (≈ 0.2–0.3 % de sal).','0.06–0.10 % (≈ 0.2–0.3 % salt).')],['warn',E('Lactación: 0.10 %.','Lactation: 0.10 %.')]]},

  /* ---------- bloque 1 ---------- */
  categoria:{c:E('El tipo de animal define qué ecuaciones usa el modelo: crecimiento (energía y proteína retenidas) o vaca (mantenimiento + gestación + leche), y los límites prácticos de forraje, fibra y grasa.','The animal type sets which equations the model uses: growth (retained energy and protein) or cow (maintenance + pregnancy + milk), and the practical limits for forage, fiber and fat.'),
    s:[['ok',E('Elige la etapa real del lote; para varias etapas usa el Programa (Bloque 7).','Pick the actual stage of the group; for several stages use the Program (Block 7).')]]},
  biotipo:{c:E('El biotipo cambia el gasto de mantenimiento (cebú −10 %, cruzas −5 %, lecheros +20 %; NRC, 1996), el tamaño adulto y la composición de la ganancia.','Biotype changes maintenance cost (zebu −10 %, crosses −5 %, dairy +20 %; NRC, 1996), mature size and gain composition.'),
    s:[['info',E('Para razas no listadas elige la más parecida y ajusta el peso final en el Bloque 2.','For breeds not listed pick the closest one and adjust final weight in Block 2.')]]},
  sexo:{c:E('Los toretes enteros gastan 15 % más en mantenimiento pero depositan más músculo; las vaquillas engrasan a menor peso.','Intact bulls spend 15 % more on maintenance but deposit more muscle; heifers fatten at lighter weights.'),
    s:[['info',E('El modelo ajusta el peso final equivalente: vaquillas × 0.82, toretes × 1.15.','The model adjusts the equivalent final weight: heifers × 0.82, bulls × 1.15.')]]},

  /* ---------- bloque 2 ---------- */
  pv:{c:E('Peso vivo promedio del lote en la etapa (lleno). El modelo usa el peso vacío en ayuno: 96 % del peso vivo.','Average live weight of the group in the stage (full). The model uses shrunk weight: 96 % of live weight.'),
    s:[['ok',E('Pesa una muestra representativa por la mañana, antes de dar de comer.','Weigh a representative sample in the morning, before feeding.')]]},
  pf:{c:E('Peso al que este tipo de animal llegaría al engrasamiento objetivo (peso final de referencia). Con él se calcula el peso equivalente y, por tanto, cuánta grasa y cuánta proteína lleva cada kilo ganado.','Weight at which this kind of animal would reach the target fatness (reference final weight). It sets the equivalent weight and, therefore, how much fat and protein each kilo of gain carries.'),
    s:[['info',E('No es el peso de venta: un torete puede venderse antes de llegar a él.','It is not the sale weight: a bull may be sold before reaching it.')],['ok',E('Británicos ≈ 540 kg, continentales ≈ 600, cebú ≈ 500 (novillos).','British ≈ 540 kg, continental ≈ 600, zebu ≈ 500 (steers).')]]},
  mw:{c:E('Peso adulto de la vaca con condición corporal media. Para vaquillas fija el ritmo de crecimiento hacia el empadre.','Mature cow weight at medium body condition. For heifers it sets the growth path to breeding.'),
    s:[['ok',E('Empadre de vaquillas al 60–65 % del peso adulto.','Breed heifers at 60–65 % of mature weight.')]]},
  adg:{c:E('Ganancia diaria de peso que quieres lograr. Con ella se calcula la energía y la proteína retenidas (NASEM, 2016).','Average daily gain you want to achieve. Retained energy and protein are computed from it (NASEM, 2016).'),
    s:[['ok',E('Engorda 1.3–1.8 kg/d; desarrollo 0.7–1.1; vaquillas 0.5–0.7.','Finishing 1.3–1.8 kg/d; growing 0.7–1.1; heifers 0.5–0.7.')],['warn',E('Si no hay solución, baja la meta o agrega energía.','If there is no solution, lower the target or add energy.')]]},
  srw:{c:E('Peso de referencia estándar (SRW): el peso vacío al que un animal de tamaño medio alcanza cierto porcentaje de grasa corporal. NASEM (2016) usa 478 kg para 28 % de grasa (calidad Choice).','Standard reference weight (SRW): the shrunk weight at which a medium-frame animal reaches a given body-fat percentage. NASEM (2016) uses 478 kg for 28 % body fat (Choice quality).'),
    s:[['info',E('435 kg (25 %) para canales magras; 462 kg (27 %) intermedio.','435 kg (25 %) for lean carcasses; 462 kg (27 %) intermediate.')]]},
  eqsbw:{c:E('Peso equivalente: el peso del animal llevado a la escala del animal de referencia. Un animal de peso equivalente alto deposita más grasa por kilo ganado y necesita más energía por kilo.','Equivalent weight: the animal’s weight rescaled to the reference animal. A high equivalent weight deposits more fat per kilo gained and needs more energy per kilo.'),
    s:[['info',E('Menos de 300 kg: ganancia rica en proteína (mejor eficiencia de la proteína).','Below 300 kg: protein-rich gain (better protein efficiency).')]]},
  dmi:{c:E('Consumo de materia seca por animal por día. RatioBos lo predice con NRC (1996) y NASEM (2016) a partir del peso y la ENm de la dieta, y lo ajusta por raza, engrasamiento, implante, ionóforo, temperatura y lodo.','Dry matter intake per head per day. RatioBos predicts it with NRC (1996) and NASEM (2016) from weight and dietary NEm, and adjusts it for breed, fatness, implant, ionophore, temperature and mud.'),
    s:[['ok',E('Si tienes registros del corral, escríbelo: el consumo real es el dato que más mejora la dieta.','If you have pen records, enter it: actual intake is the input that most improves the diet.')],['info',E('Engorda: 2.0–2.4 % del peso vivo; vacas 1.8–2.5 %.','Feedlot: 2.0–2.4 % of body weight; cows 1.8–2.5 %.')]]},
  diasGest:{c:E('Días de gestación. Las necesidades del feto crecen exponencialmente: en el último tercio (> 190 d) se suman energía, proteína, calcio y fósforo.','Days of pregnancy. Fetal needs grow exponentially: in the last trimester (> 190 d) energy, protein, calcium and phosphorus are added.'),
    s:[['info',E('Gestación total ≈ 283 días.','Total gestation ≈ 283 days.')]]},
  pn:{c:E('Peso esperado del becerro al nacer; escala las necesidades de la gestación.','Expected calf birth weight; scales the requirements of pregnancy.'),
    s:[['info',E('Cebú 28–32 kg; británico 32–36; continental 36–42.','Zebu 28–32 kg; British 32–36; continental 36–42.')]]},
  leche:{c:E('Producción de leche por día. La energía de la leche (ENl) se calcula con su grasa y se suma al mantenimiento; la proteína láctea se convierte con 65 % de eficiencia.','Milk yield per day. Milk energy (NEl) is computed from its fat and added to maintenance; milk protein is converted at 65 % efficiency.'),
    s:[['info',E('Vacas de carne: pico de 6–12 kg/d a las 8–9 semanas.','Beef cows: peak of 6–12 kg/d at 8–9 weeks.')]]},
  grasaL:{c:E('Grasa de la leche (%). Determina su contenido de energía.','Milk fat (%). Determines its energy content.'), s:[['info',E('Ganado de carne: 3.5–4.5 %.','Beef cattle: 3.5–4.5 %.')]]},
  protL:{c:E('Proteína de la leche (%).','Milk protein (%).'), s:[['info',E('Ganado de carne: 3.2–3.6 %.','Beef cattle: 3.2–3.6 %.')]]},
  nemSup:{c:E('ENm de la dieta con la que se calcularon los valores de esta tabla. Al formular, RatioBos la ajusta sola hasta que coincide con la de la dieta obtenida.','Dietary NEm used to compute the values in this table. When formulating, RatioBos adjusts it automatically until it matches the resulting diet.'),
    s:[['ok',E('No necesitas cambiarla: el ajuste iterativo la corrige.','No need to change it: the iterative adjustment corrects it.')]]},
  minmax:{c:E('Mínimo y máximo de cada nutriente por kg de materia seca: son las restricciones del modelo. Una casilla vacía no restringe.','Minimum and maximum of each nutrient per kg of dry matter: the model’s constraints. An empty cell imposes no constraint.'),
    s:[['ok',E('Los valores de energía, proteína metabolizable, Ca y P salen de las ecuaciones del animal.','Energy, metabolizable protein, Ca and P values come from the animal equations.')],['warn',E('Si editas a mano, la app deja de recalcularlos con el animal.','If you edit them by hand, the app stops recomputing them from the animal.')]]},
  reqDia:{c:E('Requerimientos por animal por día (método factorial): mantenimiento + crecimiento + gestación + leche.','Requirements per head per day (factorial method): maintenance + growth + pregnancy + milk.'),
    s:[['info',E('Divididos entre el consumo dan la concentración que debe tener la dieta.','Divided by intake they give the concentration the diet must have.')]]},

  /* ---------- bloque 3 ---------- */
  tPrev:{c:E('Temperatura media del mes anterior. El animal se aclimata: con frío previo sube su mantenimiento y con calor baja (0.0007 Mcal/kg⁰·⁷⁵ por °C respecto a 20 °C; NRC, 1996).','Mean temperature of the previous month. Animals acclimate: after cold, maintenance rises; after heat, it falls (0.0007 Mcal/kg⁰·⁷⁵ per °C relative to 20 °C; NRC, 1996).'),
    s:[['info',E('20 °C: sin ajuste.','20 °C: no adjustment.')]]},
  tAct:{c:E('Temperatura media actual. Ajusta el consumo: con calor (> 25 °C) baja 10 %, y más de 35 % si no refresca en la noche; con frío sube.','Current mean temperature. Adjusts intake: in heat (> 25 °C) it falls 10 %, and over 35 % if nights stay hot; in cold it rises.'),
    s:[['ok',E('15–25 °C: consumo normal.','15–25 °C: normal intake.')],['warn',E('> 25 °C: ofrece sombra, agua fresca y alimenta en las horas frescas.','> 25 °C: provide shade, cool water and feed in cool hours.')]]},
  noche:{c:E('Si la temperatura baja de 20 °C por la noche, el animal disipa el calor del día y el consumo cae menos.','If night temperatures drop below 20 °C, animals shed the day’s heat and intake falls less.'), s:[['info',E('Común en el norte y el altiplano; raro en la costa tropical.','Common in the north and highlands; rare on the tropical coast.')]]},
  jadeo:{c:E('El jadeo indica estrés calórico: el animal gasta energía para enfriarse. Jadeo rápido +7 % y con boca abierta +18 % al mantenimiento (NRC, 1996).','Panting signals heat stress: the animal spends energy to cool down. Rapid panting +7 % and open-mouth panting +18 % to maintenance (NRC, 1996).'),
    s:[['bad',E('Boca abierta: emergencia; agua, sombra y aspersión.','Open mouth: emergency; water, shade and sprinkling.')]]},
  lodo:{c:E('Profundidad del lodo en el corral. Cada centímetro reduce ≈ 1 % el consumo.','Mud depth in the pen. Each centimeter cuts intake by ≈ 1 %.'), s:[['warn',E('Más de 10 cm: mejora el drenaje y los montículos.','Over 10 cm: improve drainage and mounds.')]]},
  implante:{c:E('Los implantes anabólicos aumentan la ganancia y el consumo. Sin implante el consumo esperado es 6 % menor (NRC, 1996).','Anabolic implants increase gain and intake. Without an implant expected intake is 6 % lower (NRC, 1996).'),
    s:[['info',E('Respeta los tiempos de retiro y las normas de tu mercado.','Respect withdrawal times and your market’s rules.')]]},
  ionoforo:{c:E('Los ionóforos (monensina, lasalocida) cambian la fermentación hacia propionato: la dieta rinde ≈ 12 % más energía de mantenimiento y el consumo baja ≈ 3 %.','Ionophores (monensin, lasalocid) shift fermentation toward propionate: the diet yields ≈ 12 % more maintenance energy and intake falls ≈ 3 %.'),
    s:[['ok',E('Estándar en engordas; también reduce timpanismo y coccidiosis.','Standard in feedlots; also reduces bloat and coccidiosis.')]]},
  cabezas:{c:E('Número de animales del corral o lote; sirve para calcular el alimento diario total.','Number of animals in the pen or group; used to compute total daily feed.'), s:[['info',E('Resta la mortalidad esperada.','Subtract expected deaths.')]]},
  mezcla:{c:E('Capacidad del carro mezclador o de la mezcla en kg tal como se ofrece. La hoja de mezclado da los kilos de cada ingrediente húmedo.','Mixer wagon or batch capacity in kg as fed. The mixing sheet gives kilos of each wet ingredient.'),
    s:[['ok',E('Carga primero los forrajes y al final los ingredientes pequeños premezclados.','Load forages first and pre-mixed small ingredients last.')]]},
  compra:{c:E('Precio de compra por kg de peso vivo del animal que entra al corral.','Purchase price per kg live weight of the animal entering the pen.'), s:[['info',E('Úsalo para el punto de equilibrio del Programa.','Used for the Program break-even.')]]},
  venta:{c:E('Precio de venta por kg de peso vivo al salir del corral.','Sale price per kg live weight when leaving the pen.'), s:[['info',E('Si es menor que el de compra, la ganancia de peso debe pagar el diferencial.','If lower than the purchase price, weight gain must pay for the spread.')]]},
  otrosDia:{c:E('Costos distintos del alimento por animal por día: mano de obra, sanidad, intereses, instalaciones.','Non-feed costs per head per day: labor, health, interest, facilities.'), s:[['info',E('En México suelen ser 15–25 % del costo diario total.','In Mexico they are usually 15–25 % of total daily cost.')]]},

  /* ---------- bloques 4–5 ---------- */
  MS:{c:E('Materia seca: lo que queda al quitar el agua. Los bovinos se formulan en base seca porque los forrajes y ensilajes tienen mucha agua; la app convierte a base húmeda para mezclar y comprar.','Dry matter: what remains after removing water. Cattle are formulated on a dry basis because forages and silages hold lots of water; the app converts to as-fed for mixing and buying.'),
    s:[['warn',E('Mide la MS de ensilajes cada semana: si cambia, cambia la mezcla.','Measure silage DM weekly: if it changes, so does the mix.')]]},
  pef:{c:E('Factor de efectividad física (0–1): qué tanto estimula la rumia una partícula. Heno largo = 1; grano molido ≈ 0.2–0.4.','Physical effectiveness factor (0–1): how much a particle stimulates rumination. Long hay = 1; ground grain ≈ 0.2–0.4.'), s:[['info',E('FDNfe = FDN × factor.','peNDF = NDF × factor.')]]},
  precio:{c:E('Precio por kg puesto en el rancho, tal como se compra (húmedo). La app lo convierte a precio por kg de materia seca, que es lo que se minimiza.','Price per kg delivered to the ranch, as bought (wet). The app converts it to price per kg of dry matter, which is what is minimized.'),
    s:[['warn',E('Un ensilaje barato por kg puede salir caro por kg de MS.','A cheap silage per kg can be expensive per kg of DM.')]]},
  precioMS:{c:E('Precio por kg de materia seca = precio tal como se ofrece ÷ (MS/100).','Price per kg of dry matter = as-fed price ÷ (DM/100).'), s:[['info',E('Compara ingredientes siempre en esta base.','Always compare ingredients on this basis.')]]},
  incl:{c:E('Límites de inclusión en % de la materia seca, por razones de salud, palatabilidad o manejo.','Inclusion limits in % of dry matter, for health, palatability or handling reasons.'),
    s:[['ok',E('Mismo valor en mínimo y máximo = inclusión fija (premezcla).','Same value as min and max = fixed inclusion (premix).')],['warn',E('Urea ≤ 1 %; grasa añadida ≤ 3–4 %; semilla de algodón ≤ 15 %; DDGS ≤ 30–40 %.','Urea ≤ 1 %; added fat ≤ 3–4 %; whole cottonseed ≤ 15 %; DDGS ≤ 30–40 %.')]]},
  pMcal:{c:E('Costo de 1 Mcal de ENg aportada por el ingrediente. Compara fuentes de energía para engorda.','Cost of 1 Mcal of NEg supplied by the ingredient. Compares energy sources for finishing.'), s:[['ok',E('El más bajo es tu energía más barata.','The lowest is your cheapest energy.')]]},
  ppc:{c:E('Costo de 1 kg de proteína cruda aportada por el ingrediente (base seca).','Cost of 1 kg of crude protein supplied by the ingredient (dry basis).'), s:[['ok',E('Compara junto con su degradabilidad: no es lo mismo urea que harina de pescado.','Compare along with degradability: urea is not the same as fish meal.')]]},
  base:{c:E('Materia seca (MS): la fórmula nutricional. Tal como se ofrece (TCO, base húmeda): lo que pesas en la báscula y compras.','Dry matter (DM): the nutritional formula. As fed (wet basis): what you weigh on the scale and buy.'),
    s:[['info',E('Cambia la vista con el selector MS / TCO.','Switch the view with the DM / AF selector.')]]},

  /* ---------- bloque 6 ---------- */
  cert:{c:E('Certificado de optimalidad: por dualidad fuerte, el costo de la fórmula (primal) debe igualar el valor dual. La brecha y la violación miden el error numérico.','Optimality certificate: by strong duality, the formula cost (primal) must equal the dual value. The gap and violation measure numerical error.'),
    s:[['ok',E('Menores a 1×10⁻⁶: óptimo garantizado.','Below 1×10⁻⁶: guaranteed optimum.')]]},
  iter:{c:E('Ajuste iterativo: la ENg que necesita la dieta depende de su propia ENm (alimento que se va en mantenimiento) y el consumo también. RatioBos resuelve, actualiza la ENm y vuelve a resolver hasta que coinciden (cambio < 0.002 Mcal/kg).','Iterative adjustment: the NEg the diet needs depends on its own NEm (feed spent on maintenance), and so does intake. RatioBos solves, updates NEm and solves again until they agree (change < 0.002 Mcal/kg).'),
    s:[['ok',E('Converge en 2–6 vueltas.','Converges in 2–6 rounds.')],['warn',E('Si no converge, la meta de ganancia está en el límite de lo posible.','If it does not converge, the gain target is at the edge of feasibility.')]]},
  costoMS:{c:E('Costo por kg de materia seca de la dieta; es lo que el modelo hace mínimo.','Diet cost per kg of dry matter; it is what the model minimizes.'), s:[['info',E('Compara dietas mejor por costo por kg de ganancia.','Compare diets better by cost per kg of gain.')]]},
  costoTCO:{c:E('Costo por kg o tonelada de la mezcla tal como se ofrece (húmeda).','Cost per kg or tonne of the mix as fed (wet).'), s:[['info',E('Es el precio que verías si compraras la ración hecha.','It is the price you would see if you bought the mixed ration.')]]},
  costoDia:{c:E('Costo de alimento por animal por día = consumo de MS × costo por kg de MS.','Feed cost per head per day = DM intake × cost per kg DM.'), s:[['info',E('Multiplica por los días en corral para el costo total.','Multiply by days on feed for the total cost.')]]},
  costoKgGan:{c:E('Costo de alimento por kg de peso ganado = costo diario ÷ ganancia diaria. Es el criterio económico más importante de la engorda.','Feed cost per kg of weight gained = daily cost ÷ daily gain. The most important economic criterion in the feedlot.'),
    s:[['ok',E('Debe ser menor que el precio de venta por kg.','It must be lower than the sale price per kg.')],['warn',E('Una dieta más cara por tonelada puede ganar aquí.','A diet costlier per tonne can win here.')]]},
  adgPred:{c:E('Ganancia diaria que permite la dieta formulada con el consumo esperado: la menor entre la que permite la energía (EM) y la que permite la proteína metabolizable (PM).','Daily gain allowed by the formulated diet at the expected intake: the lower of energy-allowable and metabolizable-protein-allowable gain.'),
    s:[['ok',E('Igual o un poco mayor que tu meta.','Equal to or slightly above your target.')],['info',E('Si la limita la proteína, revisa la PM y el balance de PDR.','If protein limits it, check MP and RDP balance.')]]},
  conv:{c:E('Conversión alimenticia: kg de materia seca consumida por kg de peso ganado. Menos es mejor.','Feed conversion: kg of dry matter eaten per kg of weight gained. Lower is better.'),
    s:[['ok',E('Finalización 5.5–7; desarrollo 6–9.','Finishing 5.5–7; growing 6–9.')]]},
  balE:{c:E('Balance de energía: lo que aporta la dieta menos lo que el animal necesita. En vacas, un balance negativo significa que pierde peso y condición corporal.','Energy balance: what the diet supplies minus what the animal needs. In cows a negative balance means weight and body-condition loss.'),
    s:[['ok',E('Cercano a cero o positivo.','Near zero or positive.')],['bad',E('Negativo en el último tercio o la lactación: baja la preñez siguiente.','Negative in late gestation or lactation: next pregnancy rate falls.')]]},
  balPM:{c:E('Balance de proteína metabolizable diario: aporte menos requerimiento.','Daily metabolizable-protein balance: supply minus requirement.'), s:[['ok',E('0 a +10 %.','0 to +10 %.')],['bad',E('Negativo: la proteína limita la ganancia o la leche.','Negative: protein limits gain or milk.')]]},
  ch4:{c:E('Metano entérico estimado con el método IPCC (2019, Nivel 2): energía bruta consumida × Ym. Ym va de 3 % (engorda con más de 90 % de concentrado) a 7 % (forraje de baja calidad).','Enteric methane estimated with the IPCC (2019, Tier 2) method: gross energy intake × Ym. Ym ranges from 3 % (feedlot >90 % concentrate) to 7 % (low-quality forage).'),
    s:[['info',E('Dietas más digestibles producen menos metano por kg de carne.','More digestible diets produce less methane per kg of beef.')],['ok',E('Engorda: 15–25 g de CH₄ por kg de ganancia.','Feedlot: 15–25 g CH₄ per kg of gain.')]]},
  nExc:{c:E('Nitrógeno excretado = nitrógeno consumido − retenido en la ganancia, el feto o la leche. Es la base del impacto ambiental del corral (amoniaco, nitratos).','Excreted nitrogen = nitrogen eaten − retained in gain, fetus or milk. The basis of the pen’s environmental footprint (ammonia, nitrates).'),
    s:[['ok',E('Ajustar la proteína al requerimiento reduce la excreción.','Matching protein to requirements cuts excretion.')]]},
  marg:{c:E('Precio sombra: cuánto cambia el costo por tonelada de MS si el requerimiento sube 1 %. Viene de la solución dual del modelo.','Shadow price: how much the cost per tonne of DM changes if the requirement rises 1 %. Comes from the dual solution.'),
    s:[['info',E('Cero: ese nutriente sale gratis.','Zero: that nutrient comes free.')],['warn',E('Alto: ese requerimiento es caro; confirma que esté justificado.','High: that requirement is expensive; make sure it is justified.')]]},
  estado:{c:E('Una restricción limitante (activa) es la que fija el costo: el nutriente quedó justo en su mínimo o máximo.','A binding (active) constraint sets the cost: the nutrient sits exactly at its minimum or maximum.'), s:[['info',E('Revísalas primero.','Review them first.')]]},
  cumpl:{c:E('Aporte de la dieta como % del requerimiento mínimo. La línea vertical marca el 100 %.','Diet supply as % of the minimum requirement. The vertical line marks 100 %.'), s:[['ok',E('100–110 %: ajustado.','100–110 %: tight.')],['warn',E('Más de 115 %: exceso (barra terracota).','Above 115 %: excess (terracotta bar).')]]},
  CaP:{c:E('Relación calcio : fósforo. Con dietas de grano el fósforo sobra y hay que subir el calcio para evitar cálculos urinarios.','Calcium : phosphorus ratio. Grain diets carry surplus P, so Ca must rise to prevent urinary calculi.'), s:[['ok',E('1.5–2.5 : 1.','1.5–2.5 : 1.')],['bad',E('Menos de 1.2 : 1: riesgo de urolitiasis en machos.','Below 1.2 : 1: urolithiasis risk in males.')]]},
  forcon:{c:E('Relación forraje : concentrado en la materia seca.','Forage : concentrate ratio in dry matter.'), s:[['info',E('Finalización 10:90; desarrollo 40:60 a 60:40.','Finishing 10:90; growing 40:60 to 60:40.')]]},
  acidosis:{c:E('Semáforo de salud ruminal: combina fibra efectiva, forraje, grasa, urea y azufre para anticipar acidosis, timpanismo, intoxicación por amoniaco y polioencefalomalacia.','Rumen-health traffic light: combines effective fiber, forage, fat, urea and sulfur to anticipate acidosis, bloat, ammonia toxicity and polioencephalomalacia.'),
    s:[['ok',E('Verde: dentro de rangos seguros.','Green: within safe ranges.')],['warn',E('Ámbar: vigila el comedero y las heces.','Amber: watch the bunk and manure.')],['bad',E('Rojo: corrige antes de ofrecer la dieta.','Red: fix before feeding the diet.')]]},
  entrada:{c:E('Precio de entrada: el precio (por kg tal como se ofrece) al que un ingrediente no usado empezaría a entrar a la fórmula.','Entry price: the price (per kg as fed) at which an unused ingredient would start entering the formula.'),
    s:[['ok',E('Si tu proveedor te lo da a ese precio o menos, vuelve a formular.','If your supplier offers it at that price or lower, reformulate.')]]},
  limEf:{c:E('Efecto en el costo por tonelada de MS de mover un límite de inclusión 1 punto porcentual.','Effect on cost per tonne of DM of moving an inclusion limit by one percentage point.'), s:[['warn',E('Negativo: relajar ese límite abarata la dieta.','Negative: relaxing that limit makes the diet cheaper.')]]},
  evaluar:{c:E('Compara una fórmula que ya usas (en % de MS) contra los requerimientos y la fórmula óptima.','Compares a formula you already use (in % of DM) against the requirements and the optimal formula.'), s:[['info',E('La diferencia × toneladas al año = ahorro posible.','The difference × tonnes per year = possible savings.')]]},

  /* ---------- bloque 7 ---------- */
  dof:{c:E('Días en corral: los que tarda el animal en ir del peso de entrada al de venta con las dietas del programa, simulando el crecimiento día a día.','Days on feed: how long the animal takes from entry to sale weight with the program diets, simulating growth day by day.'), s:[['info',E('Engorda típica: 90–150 días.','Typical feedlot: 90–150 days.')]]},
  equilibrio:{c:E('Precio de venta de equilibrio: el precio por kg al que la venta apenas paga la compra del animal, el alimento y los otros costos.','Break-even sale price: the price per kg at which the sale just covers the animal purchase, feed and other costs.'),
    s:[['ok',E('Si tu precio de venta es mayor, el lote deja utilidad.','If your sale price is higher, the group is profitable.')]]},
  margen:{c:E('Utilidad por cabeza = venta − compra − alimento − otros costos.','Profit per head = sale − purchase − feed − other costs.'), s:[['info',E('Sin incluir mortalidad ni impuestos.','Excluding deaths and taxes.')]]},
  costoVaca:{c:E('Costo de alimento por vaca al año, sumando las cuatro etapas del ciclo.','Feed cost per cow per year, adding the four stages of the cycle.'), s:[['info',E('Divídelo entre los kg de becerro destetado para el costo por kg de becerro.','Divide by kg of weaned calf for cost per kg of calf.')]]},

  /* ---------- validación ---------- */
  mape:{c:E('Error absoluto medio porcentual (MAPE) entre el análisis calculado que publica cada artículo y el que calcula la app con su propia matriz de ingredientes.','Mean absolute percentage error (MAPE) between the calculated analysis each paper reports and the one the app computes with its own ingredient matrix.'),
    s:[['ok',E('Menos de 3 %: concordancia excelente.','Below 3 %: excellent agreement.')],['info',E('3–8 %: aceptable; se explica por diferencias de tabla de ingredientes.','3–8 %: acceptable; explained by feed-table differences.')]]},
  reform:{c:E('Prueba del optimizador: se pide la dieta más barata con al menos el mismo aporte que la fórmula publicada. Debe dar una igual o más barata.','Optimizer test: ask for the cheapest diet supplying at least as much as the published formula. It must return one that is equal or cheaper.'),
    s:[['ok',E('Igual o más barata: el optimizador es correcto.','Equal or cheaper: the optimizer is correct.')]]},
  eneObs:{c:E('Energía neta observada (Zinn y Shen, 1998): a partir del peso, la ganancia y el consumo medidos se despeja la ENm de la dieta. RatioBos repite el cálculo con los datos de cada artículo y lo compara con el valor publicado.','Observed net energy (Zinn and Shen, 1998): dietary NEm is solved from measured weight, gain and intake. RatioBos repeats the calculation with each paper’s data and compares it with the published value.'),
    s:[['ok',E('Diferencias menores a 2 %: el método está bien implementado.','Differences below 2 %: the method is correctly implemented.')]]},
  predADG:{c:E('Ganancia que predice RatioBos con la dieta publicada, el consumo observado y los valores de tabla, comparada con la ganancia medida.','Gain predicted by RatioBos from the published diet, observed intake and table values, compared with measured gain.'),
    s:[['info',E('Diferencias de ±10 % son normales: la energía real de una dieta cambia con el procesamiento del grano y el manejo.','Differences of ±10 % are normal: a diet’s real energy changes with grain processing and management.')]]},

  /* ---------- región e infraestructura ---------- */
  ith:{c:E('Índice de temperatura y humedad: ITH = 0.81·T + (HR/100)·(T − 14.4) + 46.4. Resume el calor que siente el animal; la humedad lo agrava porque impide enfriarse sudando y jadeando.','Temperature–humidity index: THI = 0.81·T + (RH/100)·(T − 14.4) + 46.4. Summarizes the heat the animal feels; humidity worsens it by hindering cooling through sweating and panting.'),
    s:[['ok',E('Menos de 75: normal.','Below 75: normal.')],['info',E('75–78: alerta.','75–78: alert.')],['warn',E('79–83: peligro; jadeo rápido.','79–83: danger; rapid panting.')],['bad',E('84 o más: emergencia.','84 or more: emergency.')]]},
  sombra:{c:E('La sombra corta la radiación solar, que puede sumar el equivalente a varios grados de temperatura. Más área por animal y estructuras altas y ventiladas alivian más.','Shade blocks solar radiation, which can add the equivalent of several degrees. More area per head and tall, ventilated structures relieve more.'),
    s:[['warn',E('Lámina de 1.3 m² por animal: alivio pequeño.','1.3 m² sheet metal per head: small relief.')],['ok',E('2.5–4 m² por animal o domo con ventiladores: recomendable en clima cálido.','2.5–4 m² per head or a dome with fans: recommended in hot climates.')]]},
  piso:{c:E('El lodo hace que el animal gaste energía al moverse, ensucia el pelo (pierde aislamiento) y baja el consumo ≈ 1 % por cm.','Mud makes animals spend energy moving, dirties the coat (losing insulation) and cuts intake ≈ 1 % per cm.'),
    s:[['ok',E('Piso firme o tierra con pendiente y montículos.','Firm floor or sloped dirt with mounds.')],['bad',E('Tierra sin drenaje en lluvias: lodo de 10–15 cm.','Undrained dirt in the rains: 10–15 cm of mud.')]]},
  sistemaP:{c:E('En pastoreo el animal camina y busca su alimento: el mantenimiento sube 10 % en terreno plano y 20 % en lomerío (NRC, 1996).','On pasture the animal walks and forages: maintenance rises 10 % on flat land and 20 % on hills (NRC, 1996).'),
    s:[['info',E('En corral el gasto de actividad es mínimo.','In a pen the activity cost is minimal.')]]},
  sAgua:{c:E('Sulfatos del agua de bebida (mg/L). Su azufre se suma al de la ración; la app descuenta ese aporte del máximo de azufre permitido.','Drinking-water sulfates (mg/L). Their sulfur adds to the ration’s; the app subtracts it from the maximum sulfur allowed.'),
    s:[['ok',E('Menos de 500 mg/L.','Below 500 mg/L.')],['warn',E('500–1,000 mg/L: limita DDGS y melaza.','500–1,000 mg/L: limit DDGS and molasses.')],['bad',E('Más de 1,000 mg/L: riesgo de polioencefalomalacia.','Over 1,000 mg/L: polioencephalomalacia risk.')]]},
  regionComp:{c:E('El mismo animal y la misma lista de ingredientes formulados con el clima de la temporada y los precios estimados de cada región.','The same animal and ingredient list formulated with each region’s seasonal climate and estimated prices.'),
    s:[['info',E('La barra terracota es tu región.','The terracotta bar is your region.')]]},

  /* ---------- tablero ---------- */
  ea:{c:E('Eficiencia alimenticia = kg ganados ÷ kg de materia seca consumida. Más alto es mejor.','Feed efficiency = kg gained ÷ kg of dry matter eaten. Higher is better.'),
    s:[['ok',E('Finalización 0.14–0.19; becerros 0.20–0.28.','Finishing 0.14–0.19; calves 0.20–0.28.')]]},
  bc:{c:E('Relación beneficio : costo = ingresos ÷ costos. Mayor que 1: la actividad deja utilidad.','Benefit : cost ratio = revenue ÷ costs. Above 1: the activity is profitable.'),
    s:[['ok',E('Mayor que 1.1.','Above 1.1.')],['warn',E('Entre 1.0 y 1.1: margen estrecho.','Between 1.0 and 1.1: thin margin.')],['bad',E('Menor que 1: pérdidas.','Below 1: losses.')]]},
  optimo:{c:E('La app formula raciones para varias metas de ganancia y calcula el margen diario de cada una (valor de la ganancia − alimento − otros costos). El punto más alto es la ganancia económicamente óptima.','The app formulates rations for several gain targets and computes each one’s daily margin (value of gain − feed − other costs). The highest point is the economically optimal gain.'),
    s:[['info',E('Depende de tus precios: si sube el grano, el óptimo baja.','It depends on your prices: if grain rises, the optimum falls.')]]},
  sensib:{c:E('Cómo cambian el costo y el uso del ingrediente que más pesa en la ración cuando su precio sube o baja hasta 30 %.','How cost and use of the ration’s heaviest ingredient change when its price moves up or down by up to 30 %.'),
    s:[['info',E('Una curva plana indica que hay buenos sustitutos.','A flat curve means there are good substitutes.')]]},
  refs:{c:E('Desempeño medido en engordas experimentales y comerciales publicadas, como referencia para tus resultados.','Performance measured in published experimental and commercial feedlots, as a benchmark for your results.'),
    s:[['info',E('Compara animales de peso y biotipo parecidos.','Compare animals of similar weight and biotype.')]]},

  /* ---------- sostenibilidad ---------- */
  sostenible:{c:E('Semáforo de la carga ambiental de la ración, en el sentido de sostenibilidad de la FAO: producir con menos recursos y menos externalidades negativas.','Traffic light for the ration’s environmental load, in FAO’s sense of sustainability: producing with fewer resources and fewer negative externalities.'),
    s:[['ok',E('Verde: carga baja para este tipo de producción.','Green: low load for this type of production.')],['warn',E('Ámbar: hay margen para mejorar.','Amber: room for improvement.')],['bad',E('Rojo: prioridad de mejora.','Red: improvement priority.')]]},
  gei:{c:E('Gases de efecto invernadero en CO₂ equivalente (IPCC AR6: CH₄ × 27, N₂O × 273): metano entérico y del estiércol, óxido nitroso del estiércol y emisiones de producir el alimento.','Greenhouse gases in CO₂ equivalents (IPCC AR6: CH₄ × 27, N₂O × 273): enteric and manure methane, manure nitrous oxide and feed-production emissions.'),
    s:[['ok',E('Engorda intensiva: ≈ 8–15 kg CO₂e por kg ganado.','Intensive feedlot: ≈ 8–15 kg CO₂e per kg gained.')],['warn',E('Raciones de forraje de baja calidad emiten más por kg de carne.','Low-quality forage rations emit more per kg of beef.')]]},
  aguaB:{c:E('Agua que bebe el animal: ≈ 3.5 L por kg de MS en clima templado y ≈ 5 L en calor.','Water the animal drinks: ≈ 3.5 L per kg DM in temperate climates and ≈ 5 L in heat.'), s:[['info',E('Sube mucho con calor y con dietas saladas.','Rises sharply with heat and salty diets.')]]},
  huellaH:{c:E('Huella hídrica verde (lluvia) + azul (riego) para producir el alimento consumido (Mekonnen y Hoekstra, 2011).','Green (rain) + blue (irrigation) water footprint to produce the feed eaten (Mekonnen and Hoekstra, 2011).'), s:[['info',E('Los subproductos y forrajes de temporal tienen huella azul baja.','By-products and rainfed forages have a low blue footprint.')]]},
  sueloA:{c:E('Superficie agrícola necesaria para producir el alimento del animal durante un año, con rendimientos medios.','Cropland needed to produce the animal’s feed for a year, at average yields.'), s:[['info',E('Los subproductos usan poca tierra propia.','By-products use little land of their own.')]]},
  sueloE:{c:E('Superficie para aplicar el estiércol sin contaminar: 170 kg de N o 25 kg de P por hectárea al año; se toma la mayor.','Land to spread manure without pollution: 170 kg N or 25 kg P per hectare per year; the larger applies.'), s:[['warn',E('Si no tienes esa superficie, composta o vende el estiércol.','If you lack that land, compost or sell the manure.')]]},
  nh3:{c:E('Amoniaco que se volatiliza de las excretas (30 % del N en corral, 21 % en pastoreo; IPCC, 2019). Causa olores, partículas finas y lluvia ácida.','Ammonia volatilized from excreta (30 % of N in drylots, 21 % on pasture; IPCC, 2019). Causes odor, fine particles and acid rain.'), s:[['ok',E('Ajustar la proteína al requerimiento lo reduce.','Matching protein to requirements reduces it.')]]},
  agGris:{c:E('Nitrógeno que se lava a los mantos de agua en climas húmedos y volumen de agua que se necesitaría para diluirlo a 10 mg/L (agua gris).','Nitrogen leached to groundwater in humid climates and the volume of water needed to dilute it to 10 mg/L (grey water).'), s:[['info',E('En climas secos la lixiviación es mínima.','In dry climates leaching is minimal.')]]},
  pExc:{c:E('Fósforo de la ración que no retiene el animal. En el suelo se acumula y en el agua causa eutrofización.','Ration phosphorus the animal does not retain. It builds up in soil and causes eutrophication in water.'), s:[['ok',E('No pases el requerimiento de P más de 10–15 %.','Do not exceed the P requirement by more than 10–15 %.')]]},
  heces:{c:E('Heces frescas estimadas (15 % de MS) a partir de la materia seca no digerida.','Estimated fresh feces (15 % DM) from undigested dry matter.'), s:[['info',E('Sin contar la orina.','Excluding urine.')]]},
  medic:{c:E('Medicamentos y aditivos por animal y por lote, clasificados por categoría y, para los antimicrobianos, por su importancia en la medicina humana según la OMS.','Medicines and additives per head and per group, classified by category and, for antimicrobials, by their importance in human medicine according to WHO.'),
    s:[['ok',E('Ionóforos y vacunas: sin importancia médica / preventivos.','Ionophores and vaccines: not medically important / preventive.')],['bad',E('Macrólidos: uso solo justificado por el veterinario.','Macrolides: use only when justified by the veterinarian.')]]},
  precioC:{c:E('Precio interno del carbono: un costo ficticio por tonelada de CO₂e que se suma al precio de cada ingrediente. Al subirlo, el modelo cambia a ingredientes con menor huella; la curva muestra cuánto cuesta reducirla.','Internal carbon price: a shadow cost per tonne of CO₂e added to each ingredient’s price. As it rises, the model shifts to lower-footprint ingredients; the curve shows what reducing it costs.'),
    s:[['info',E('El punto de equilibrio es donde cada peso extra evita más CO₂e.','The balance point is where each extra peso avoids the most CO₂e.')]]},
  valEco:{c:E('Con el consumo, los días, el precio del alimento, los otros costos y el precio del ganado que publica el artículo, RatioBos recalcula el costo total, el ingreso, el costo por kg ganado y la relación beneficio : costo.','From the intake, days, feed price, other costs and cattle price the paper publishes, RatioBos recomputes total cost, income, cost per kg gained and the benefit : cost ratio.'),
    s:[['ok',E('Diferencias menores a 1 %: las fórmulas económicas son correctas.','Differences below 1 %: the economic formulas are correct.')]]},
  valPM:{c:E('Porcentaje del requerimiento de proteína metabolizable que cubría cada ración según los autores (NRC, 2000) y según RatioBos (NASEM, 2016), con la ganancia y el consumo medidos.','Percentage of the metabolizable-protein requirement each ration covered according to the authors (NRC, 2000) and to RatioBos (NASEM, 2016), at measured gain and intake.'),
    s:[['info',E('NASEM (2016) estima menos proteína microbiana que NRC (2000): es normal que RatioBos dé valores algo menores.','NASEM (2016) estimates less microbial protein than NRC (2000): somewhat lower values from RatioBos are expected.')]]},
  huellaIng:{c:E('Factores ambientales por kg de MS del ingrediente: emisiones de producirlo, huella hídrica y superficie. Valores orientativos; reemplázalos si tienes datos de tu proveedor.','Environmental factors per kg DM of the ingredient: production emissions, water footprint and land. Indicative values; replace them if your supplier has data.'), s:[['info',E('Se usan en el Bloque 10.','Used in Block 10.')]]}
};
/* botón «?» */
function ayuda(k){ return AYUDA[k] ? `<span class="qh" tabindex="0" role="button" data-q="${k}" aria-label="${T('Ayuda','Help')}">?</span>` : ''; }
function ayudaHTML(k, titulo){
  const a = AYUDA[k]; if(!a) return '';
  return `${titulo?`<b class="qt">${titulo}</b>`:''}<p>${tx(a.c)}</p><div class="qe">${T('Escala de decisión','Decision scale')}</div><ul>${a.s.map(([n,t])=>`<li class="${n}">${tx(t)}</li>`).join('')}</ul>`;
}
(function(){
  let tip=null, cur=null;
  function show(el){
    if(!tip){ tip=document.createElement('div'); tip.id='qtip'; tip.setAttribute('role','tooltip'); document.body.appendChild(tip); }
    const k=el.dataset.q; const tit = el.dataset.qt || (el.closest('td,th,label,h3,h4,.kpi .l,.l,.f')||{}).innerText || '';
    tip.innerHTML = ayudaHTML(k, (NUT[k]?tx(NUT[k].n):tit.replace(/\?/g,'').trim()).slice(0,90)); cur=el;
    tip.classList.add('on'); show.t=Date.now();
    const r=el.getBoundingClientRect(), w=Math.min(330, window.innerWidth-24); tip.style.width=w+'px';
    let x=r.left+r.width/2-w/2; x=Math.max(12,Math.min(x,window.innerWidth-w-12));
    const h=tip.offsetHeight; let y=r.bottom+8; if(y+h>window.innerHeight-8) y=Math.max(8,r.top-h-8);
    tip.style.left=x+'px'; tip.style.top=y+'px';
  }
  function hide(){ if(tip){ tip.classList.remove('on'); } cur=null; }
  document.addEventListener('mouseover',e=>{ const el=e.target.closest&&e.target.closest('.qh'); if(el) show(el); });
  document.addEventListener('mouseout',e=>{ const el=e.target.closest&&e.target.closest('.qh'); if(el && !(e.relatedTarget&&el.contains(e.relatedTarget))) hide(); });
  document.addEventListener('focusin',e=>{ const el=e.target.closest&&e.target.closest('.qh'); if(el) show(el); });
  document.addEventListener('focusout',e=>{ if(e.target.classList&&e.target.classList.contains('qh')) hide(); });
  document.addEventListener('click',e=>{ const el=e.target.closest&&e.target.closest('.qh'); if(el){ e.preventDefault(); e.stopPropagation(); show(el); } else hide(); }, true);
  document.addEventListener('keydown',e=>{ if(e.key==='Escape') hide(); });
  window.addEventListener('scroll',()=>{ if(cur && Date.now()-(show.t||0)>400) hide(); },{passive:true});
})();
