"use strict";
/* ================= VALIDACIÓN / VALIDATION ================= */
function ingsCaso(caso){ return ING_LIB.map(ingDesdeLib).concat((caso.extra||[]).map(e=>({id:e.id, nombre:e.nombre, cat:e.cat, comp:Object.assign({},e.comp), precio:0, min:0, max:100, env:envDe(e.id)}))); }
function correrCaso(caso, fi){
  const fase = caso.fases[fi], ings = ingsCaso(caso);
  const sumaPub = fase.f.reduce((a,x)=>a+x[1],0);
  const fN = fase.f.map(([id,p])=>[id, p*100/sumaPub]);
  const formula = Object.fromEntries(fN);
  const an = analizar(formula, ings, null); an.sumaPub = sumaPub;
  const comp = Object.entries(fase.rep).map(([k,v])=>{ const app = an.nutr[k]; return {k, rep:v, app, dif:app-v, pct:(app-v)/v*100, excl:fase.excl[k]}; });
  /* prueba del optimizador: mismo aporte, mismos ingredientes → igual o más barata */
  const claves = Object.keys(fase.rep).filter(k=>!fase.excl[k] && NUT[k]);
  const fijos = ['premezcla','otros','premixea','agromix','mgo','sal','bentonita','sesqui','monocal'];
  const sub = fN.map(([id,p])=>{ const i = ings.find(x=>x.id===id); const c = Object.assign({}, i); if(fijos.includes(id)){ c.min=p; c.max=p; } else { c.min=0; c.max=100; } return c; });
  const req = {}; NUTRIENTES.forEach(n=>req[n.k]=[null,null]);
  claves.forEach(k=>{ const v = an.nutr[k]*(1-1e-6); req[k] = ['EE','FDN','S'].includes(k) ? [null, an.nutr[k]*(1+1e-6)] : [v, null]; });
  const rB = resolverModelo(construirModelo(sub, req, null));
  const igual = rB.ok && fN.every(([id,p])=>Math.abs(((rB.formula.find(x=>x.id===id)||{pct:0}).pct)-p) < 0.01);
  const recup = {r:rB, costoPub:an.costoKg, ok: rB.ok && rB.costoKg <= an.costoKg*(1+1e-6), igual};
  /* energía neta observada: se repite el cálculo de los autores con sus datos */
  const perf = (fase.perf||[]).map(p=>{ const o = eneObservada(p.pvI, p.pvF, p.adg, p.dmi, p.em, p.eg);
    const x = Object.assign({}, p, {nemApp:o.nem, negApp:o.neg, errM:100*(o.nem-p.nemObs)/p.nemObs, errG:100*(o.neg-p.negObs)/p.negObs, ratioM: p.nemObs/an.nutr.NEm});
    if(p.econ){ const e = p.econ, gan = p.pvF-p.pvI, alim = p.dmi*e.precioAlim*p.dias + e.extra, total = alim + e.otros, ingreso = gan*e.precioPV;
      x.ec = {alim, total, ingreso, ckg: total/gan, bc: ingreso/total, err: 100*(total/gan - e.pub.ckg)/e.pub.ckg}; }
    if(p.mpPct){ x.mp = proteinaObs(p, formula, ings); }
    return x; });
  return {fase, an, comp, recup, perf};
}
/* PM aportada / requerida por los animales del artículo, con las ecuaciones de RatioBos */
function proteinaObs(p, formula, ings){
  const s = estadoInicial(); s.cat = 'desarrollo'; s.biotipo = p.holstein ? 'lechero' : 'cruza'; s.sexo = 'novillo';
  s.animal = animalInicial(s.cat, s.biotipo, s.sexo); s.animal.pv = ((p.pvI+p.pvF)/2)/0.96; s.animal.adg = p.adg; s.animal.dmi = p.dmi;
  s.cond.tAct = 20; s.cond.tPrev = 20; s.cond.jadeo = 'no'; s.cond.lodo = 0; s.cond.ionoforo = true; s.cond.sistema = 'corral';
  const ctx = contexto(s), A = requerimientos(ctx, {NEm:2.0, TND:80}), an = analizar(formula, ings, p.dmi);
  const sup = an.nutr.PM*p.dmi; return {sup, req:A.d.mp, pct:100*sup/A.d.mp};
}
function resumenEcon(){ const e = []; VALIDACION.forEach(c=>c.fases.forEach((_,i)=>correrCaso(c,i).perf.forEach(p=>{ if(p.ec) e.push(Math.abs(p.ec.err)); })));
  return {n:e.length, mape:e.reduce((a,b)=>a+b,0)/(e.length||1)}; }
function resumenPM(){ const e = []; VALIDACION.forEach(c=>c.fases.forEach((_,i)=>correrCaso(c,i).perf.forEach(p=>{ if(p.mp) e.push(p.mp.pct - p.mpPct); })));
  return {n:e.length, sesgo:e.reduce((a,b)=>a+b,0)/(e.length||1), mae:e.reduce((a,b)=>a+Math.abs(b),0)/(e.length||1)}; }
function resumenValidacion(){
  const grupos = {NE:[],PC:[],FDN:[],Min:[]};
  VALIDACION.forEach(c=>c.fases.forEach((_,i)=>{ correrCaso(c,i).comp.forEach(x=>{ if(x.excl) return;
    const g = ['NEm','NEg'].includes(x.k)?'NE':x.k==='PC'?'PC':['FDN','EE'].includes(x.k)?'FDN':['Ca','P','S'].includes(x.k)?'Min':null; if(g) grupos[g].push(Math.abs(x.pct)); }); }));
  return Object.fromEntries(Object.entries(grupos).map(([k,v])=>[k,{n:v.length, mape: v.reduce((a,b)=>a+b,0)/(v.length||1), max: Math.max(0,...v)}]));
}
function resumenOptim(){ let n=0, ok=0, cert=0, igual=0;
  VALIDACION.forEach(c=>c.fases.forEach((_,i)=>{ const R = correrCaso(c,i); n++; if(R.recup.ok) ok++; if(R.recup.igual) igual++; if(R.recup.r.ok && R.recup.r.cert.ok) cert++; }));
  return {n, ok, cert, igual}; }
function resumenEnergia(){ const e = []; VALIDACION.forEach(c=>c.fases.forEach((_,i)=>correrCaso(c,i).perf.forEach(p=>{ e.push(Math.abs(p.errM)); e.push(Math.abs(p.errG)); })));
  return {n:e.length/2, mape:e.reduce((a,b)=>a+b,0)/(e.length||1), max:Math.max(0,...e)}; }
function colorPct(p){ const a=Math.abs(p); return a<=3?'ok':a<=8?'warn':'bad'; }
function renderValidacion(el){
  const caso = VALIDACION.find(c=>c.id===S.valCaso) || VALIDACION[0];
  const res = resumenValidacion(), opt = resumenOptim(), ene = resumenEnergia(), eco = resumenEcon(), pmv = resumenPM();
  const anios = VALIDACION.map(c=>+(c.cita.match(/\((\d{4})\)/)||[0,0])[1]).filter(Boolean), a0 = Math.min(...anios), a1 = Math.max(...anios);
  const etq = {NE:T('Energía neta (ENm, ENg)','Net energy (NEm, NEg)'),PC:T('Proteína cruda','Crude protein'),FDN:T('Fibra y grasa','Fiber and fat'),Min:T('Ca, P y S','Ca, P and S')};
  const nD = VALIDACION.reduce((s,c)=>s+c.fases.length,0);
  el.innerHTML = `${cabecera('validacion',T('¿La app da resultados correctos? Aquí se capturan, tal cual, dietas de engorda publicadas en revistas científicas: se compara el análisis que calcula RatioBos con el que reportan los autores, se repite su cálculo de energía neta observada con su desempeño medido y se reformulan para comprobar el optimizador.','Does the app give correct results? Here, feedlot diets published in scientific journals are entered as printed: RatioBos’s calculated analysis is compared with the authors’, their observed net-energy calculation is repeated from measured performance, and the diets are reformulated to test the optimizer.'))}
  ${teoriaDe(['validacion'])}
  <div class="card"><h3>${T('Resumen de la validación','Validation summary')}${ayuda('mape')}</h3>
    <p class="small muted" style="margin-top:0">${nD} ${T('dietas de','diets from')} ${VALIDACION.length} ${T(`artículos (México y EUA, ${a0}–${a1}). Error absoluto medio entre el análisis publicado y el que calcula la app con su propia tabla de ingredientes.`,`papers (Mexico and USA, ${a0}–${a1}). Mean absolute error between the published analysis and the one the app computes with its own feed table.`)}</p>
    <div class="kpis" style="margin:0">${Object.entries(res).map(([k,v])=>`<div class="kpi"><div class="l">${etq[k]}</div><div class="v">${fmt(v.mape,1)} %</div><div class="s">${v.n} ${T('comparaciones','comparisons')} · ${T('máx.','max.')} ${fmt(v.max,1)} %</div></div>`).join('')}
      <div class="kpi"><div class="l">${T('Energía neta observada','Observed net energy')}${ayuda('eneObs')}</div><div class="v">${fmt(ene.mape,2)} %</div><div class="s">${ene.n} ${T('grupos de animales','animal groups')} · ${T('máx.','max.')} ${fmt(ene.max,1)} %</div></div>
      <div class="kpi"><div class="l">${T('Prueba del optimizador','Optimizer test')}${ayuda('reform')}</div><div class="v">${opt.ok} / ${opt.n}</div><div class="s">${T('iguales o más baratas','equal or cheaper')} · ${opt.cert} ${T('certificadas','certified')}</div></div>
      <div class="kpi"><div class="l">${T('Economía (costo por kg ganado)','Economics (cost per kg gained)')}${ayuda('valEco')}</div><div class="v">${fmt(eco.mape,2)} %</div><div class="s">${eco.n} ${T('grupos con costos publicados','groups with published costs')}</div></div>
      <div class="kpi"><div class="l">${T('Proteína metabolizable','Metabolizable protein')}${ayuda('valPM')}</div><div class="v">${(pmv.sesgo>=0?'+':'')+fmt(pmv.sesgo,1)} pts</div><div class="s">${pmv.n} ${T('raciones · error medio','rations · mean error')} ${fmt(pmv.mae,1)} pts</div></div></div></div>
  <div class="card prod"><h3>${T('¿Puedo confiar en RatioBos?','Can I trust RatioBos?')}</h3><ul class="granja">
    <li>${T(`Se reprodujeron ${nD} dietas de engorda de ${VALIDACION.length} artículos científicos, una de ellas de un corral comercial de Sinaloa: la energía calculada difiere en promedio <b>${fmt(res.NE.mape,1)} %</b> y la proteína <b>${fmt(res.PC.mape,1)} %</b> de lo que reportaron los investigadores, una diferencia normal entre tablas de alimentos.`,`${nD} feedlot diets from ${VALIDACION.length} scientific papers were reproduced, one from a commercial pen in Sinaloa: calculated energy differs on average by <b>${fmt(res.NE.mape,1)} %</b> and protein by <b>${fmt(res.PC.mape,1)} %</b> from the researchers’ values, a normal gap between feed tables.`)}</li>
    <li>${T(`Con el peso, la ganancia y el consumo medidos en los corrales, la app calculó la energía de la dieta con un error de solo <b>${fmt(ene.mape,1)} %</b> frente a los autores.`,`From the weight, gain and intake measured in the pens, the app computed diet energy with an error of only <b>${fmt(ene.mape,1)} %</b> versus the authors.`)}</li>
    <li>${T(`En <b>${opt.ok} de ${opt.n}</b> casos el optimizador encontró una ración igual o más barata con el mismo aporte.`,`In <b>${opt.ok} of ${opt.n}</b> cases the optimizer found an equal or cheaper ration with the same supply.`)}</li></ul>
    <button class="btn ghost sm" data-vista="cien" style="margin-top:10px">${T('Ver el detalle en la vista científica','See the details in the scientist view')}</button></div>
  <div class="sci">
  <div class="card" id="pruebaSolver"><h3>${T('Prueba matemática del motor de cálculo','Mathematical test of the solver')}</h3><p class="small" style="margin:0" id="txtSolver">${tx(PRUEBA_SOLVER)}</p></div>
  <div class="opts" style="margin-bottom:18px">${VALIDACION.map(c=>`<label class="opt ${c.id===caso.id?'sel':''}"><input type="radio" name="vcaso" value="${c.id}" ${c.id===caso.id?'checked':''}><b><span class="flag">${c.bandera}</span>${esc(c.corta)}</b><small>${esc(tx(c.pais))} · ${esc(tx(c.animal))}</small></label>`).join('')}</div>
  <div class="card soft small"><b>${T('Artículo','Paper')}:</b> ${esc(caso.cita)} <a href="https://doi.org/${caso.doi}" target="_blank" rel="noopener">doi:${caso.doi}</a><br><span class="muted">${esc(tx(caso.nota))}</span></div>
  ${caso.fases.map((f,i)=>{ const R = correrCaso(caso,i); return `
  <div class="card"><h3>${esc(tx(f.nombre))}</h3>
    <div class="grid g2">
      <div><h4 style="margin-top:0">${T('Fórmula publicada (% MS)','Published formula (% DM)')}</h4><div class="tbl"><table><thead><tr><th>${T('Ingrediente','Ingredient')}</th><th class="r">%</th></tr></thead><tbody>
        ${f.f.map(([id,p])=>`<tr><td>${esc(ingNombre(id, caso.extra))}</td><td class="r">${fmt(p,2)}</td></tr>`).join('')}<tr class="tot"><td>Total</td><td class="r">${fmt(R.an.sumaPub,2)}</td></tr></tbody></table></div></div>
      <div><h4 style="margin-top:0">${T('Análisis calculado: artículo vs. RatioBos','Calculated analysis: paper vs. RatioBos')}</h4><div class="tbl"><table><thead><tr><th>${T('Nutriente','Nutrient')}</th><th class="r">${T('Artículo','Paper')}</th><th class="r">App</th><th class="r">%</th></tr></thead><tbody>
        ${R.comp.map(x=>`<tr><td>${esc(tx(NUT[x.k].n))}</td><td class="r">${fmt(x.rep,NUT[x.k].d)}</td><td class="r"><b>${fmt(x.app,NUT[x.k].d)}</b></td><td class="r"><span class="badge ${colorPct(x.pct)}">${(x.pct>=0?'+':'')+fmt(x.pct,1)}</span></td></tr>`).join('')}</tbody></table></div></div>
    </div>
    ${R.perf.length?`<h4>${T('Energía neta observada (Zinn y Shen, 1998)','Observed net energy (Zinn and Shen, 1998)')}${ayuda('eneObs')}</h4><div class="tbl"><table><thead><tr><th>${T('Tratamiento','Treatment')}</th><th class="r">${T('Peso','Weight')} kg</th><th class="r">GDP</th><th class="r">CMS</th><th class="r">ENm ${T('artículo','paper')}</th><th class="r">ENm app</th><th class="r">ENg ${T('artículo','paper')}</th><th class="r">ENg app</th><th class="r">${T('Obs./tabla','Obs./table')}</th></tr></thead><tbody>
      ${R.perf.map(p=>`<tr><td>${esc(tx(p.trat))}</td><td class="r">${fmt(p.pvI,0)}→${fmt(p.pvF,0)}</td><td class="r">${fmt(p.adg,3)}</td><td class="r">${fmt(p.dmi,2)}</td><td class="r">${fmt(p.nemObs,2)}</td><td class="r"><b>${fmt(p.nemApp,3)}</b> <span class="badge ${colorPct(p.errM)}">${(p.errM>=0?'+':'')+fmt(p.errM,1)} %</span></td><td class="r">${fmt(p.negObs,2)}</td><td class="r"><b>${fmt(p.negApp,3)}</b> <span class="badge ${colorPct(p.errG)}">${(p.errG>=0?'+':'')+fmt(p.errG,1)} %</span></td><td class="r">${fmt(p.ratioM,2)}</td></tr>`).join('')}</tbody></table></div>
      <p class="tiny muted">${T('Coeficientes usados por los autores: mantenimiento 0.077 Mcal/kg⁰·⁷⁵ (cruzas) o 0.084 (Holstein); ganancia 0.0557 (o 0.0493)·W⁰·⁷⁵·GDP¹·⁰⁹⁷. «Obs./tabla»: ENm observada entre la ENm que calcula la app con su tabla.','Coefficients used by the authors: maintenance 0.077 Mcal/kg⁰·⁷⁵ (crosses) or 0.084 (Holstein); gain 0.0557 (or 0.0493)·W⁰·⁷⁵·ADG¹·⁰⁹⁷. “Obs./table”: observed NEm divided by the NEm the app computes from its table.')}</p>`:''}
    ${R.perf.some(p=>p.ec)?`<h4>${T('Economía publicada vs. calculada por RatioBos','Published vs. RatioBos economics')}${ayuda('valEco')}</h4><div class="tbl"><table><thead><tr><th>${T('Tratamiento','Treatment')}</th><th class="r">${T('Costo total','Total cost')}</th><th class="r">${T('Ingreso','Income')}</th><th class="r">${T('Costo/kg ganado','Cost/kg gained')} ${T('artículo','paper')}</th><th class="r">App</th><th class="r">B/C</th></tr></thead><tbody>
      ${R.perf.filter(p=>p.ec).map(p=>`<tr><td>${esc(tx(p.trat))}</td><td class="r">${p.econ.moneda} ${fmt(p.ec.total,2)} <span class="muted tiny">(${fmt(p.econ.pub.total,2)})</span></td><td class="r">${p.econ.moneda} ${fmt(p.ec.ingreso,2)} <span class="muted tiny">(${fmt(p.econ.pub.ingreso,2)})</span></td><td class="r">${fmt(p.econ.pub.ckg,2)}</td><td class="r"><b>${fmt(p.ec.ckg,3)}</b> <span class="badge ${colorPct(p.ec.err)}">${(p.ec.err>=0?'+':'')+fmt(p.ec.err,1)} %</span></td><td class="r">${fmt(p.ec.bc,2)}</td></tr>`).join('')}</tbody></table></div>`:''}
    ${R.perf.some(p=>p.mp)?`<h4>${T('Proteína metabolizable: % del requerimiento','Metabolizable protein: % of requirement')}${ayuda('valPM')}</h4><div class="tbl"><table><thead><tr><th>${T('Tratamiento','Treatment')}</th><th class="r">${T('Aporte','Supply')} g/d</th><th class="r">${T('Requerimiento','Requirement')} g/d</th><th class="r">% ${T('artículo','paper')} (NRC 2000)</th><th class="r">% RatioBos (NASEM 2016)</th></tr></thead><tbody>
      ${R.perf.filter(p=>p.mp).map(p=>`<tr><td>${esc(tx(p.trat))}</td><td class="r">${fmt(p.mp.sup,0)}</td><td class="r">${fmt(p.mp.req,0)}</td><td class="r">${fmt(p.mpPct,0)}</td><td class="r"><b>${fmt(p.mp.pct,0)}</b></td></tr>`).join('')}</tbody></table></div>`:''}
    ${pintarReform(R, f, caso)}
  </div>`; }).join('')}
  </div>
  ${siguiente('validacion')}`;
  $$('input[name=vcaso]',el).forEach(r=>r.addEventListener('change',()=>{ S.valCaso=r.value; guardar(); render(); }));
}
function pintarReform(R, f, caso){
  const rB = R.recup.r;
  if(!rB.ok) return `<div class="alert warn">${T('No se pudo reformular:','Could not reformulate:')} ${esc(rB.motivo)}</div>`;
  const pub = Object.fromEntries(f.f.map(([id,p])=>[id,p*100/R.an.sumaPub]));
  return `<h4>${T('Prueba del optimizador','Optimizer test')}${ayuda('reform')}</h4>
    <div class="grid g2"><div class="tbl"><table><thead><tr><th>${T('Ingrediente','Ingredient')}</th><th class="r">${T('Artículo','Paper')}</th><th class="r">App</th></tr></thead><tbody>
      ${f.f.map(([id])=>{ const a = (rB.formula.find(x=>x.id===id)||{pct:0}).pct; return `<tr><td>${esc(ingNombre(id, caso.extra))}</td><td class="r">${fmt(pub[id],2)}</td><td class="r"><b>${fmt(a,2)}</b></td></tr>`; }).join('')}</tbody></table></div>
    <div><div class="kpis" style="grid-template-columns:1fr 1fr"><div class="kpi"><div class="l">${T('Fórmula publicada','Published formula')}</div><div class="v">${money(R.recup.costoPub*1000,0)}</div><div class="s">${T('por t MS, precios de ejemplo','per t DM, example prices')}</div></div>
      <div class="kpi"><div class="l">${T('Fórmula de la app','App formula')}</div><div class="v">${money(rB.costoKg*1000,0)}</div><div class="s">${rB.cert.ok?T('óptimo certificado','certified optimum'):''}</div></div></div>
      <div class="alert ${R.recup.ok?'ok':'bad'} small"><b>${R.recup.ok?T('✓ Correcto','✓ Correct'):T('✗ Revisar','✗ Check')}:</b> ${R.recup.igual?T('la app reencontró la fórmula publicada.','the app recovered the published formula.'):R.recup.ok?T(`con el mismo aporte encontró una ración ${money((R.recup.costoPub-rB.costoKg)*1000,0)} más barata por t de MS (con los precios de ejemplo).`,`with the same supply it found a ration ${money((R.recup.costoPub-rB.costoKg)*1000,0)} cheaper per t DM (at example prices).`):T('la app no igualó la fórmula publicada.','the app did not match the published formula.')}</div></div></div>`;
}
/* Texto de la prueba contra HiGHS: se reemplaza con el resultado real de la prueba del repositorio */
let PRUEBA_SOLVER = {es:'Se generaron al azar 500 problemas de formulación reales de la app (las 5 etapas, 6 biotipos, 9 regiones y 3 temporadas; ingredientes elegidos al azar de la biblioteca y precios entre −50 % y +50 %) y se resolvieron también con HiGHS (SciPy 1.18), un solucionador independiente de referencia. Coincidieron los 500: los 288 con solución dieron el mismo costo mínimo (diferencia relativa máxima de 4 × 10⁻¹⁴) y los 212 sin solución fueron declarados infactibles por ambos. El guion de la prueba está en la carpeta «pruebas» del repositorio.', en:'500 real app formulation problems were generated at random (all 5 stages, 6 biotypes, 9 regions and 3 seasons; ingredients drawn at random from the library and prices from −50 % to +50 %) and also solved with HiGHS (SciPy 1.18), an independent reference solver. All 500 agreed: the 288 feasible ones gave the same minimum cost (largest relative difference 4 × 10⁻¹⁴) and the 212 infeasible ones were declared infeasible by both. The test script is in the repository’s «pruebas» folder.'};

/* ================= TEORÍA / THEORY ================= */
const TEORIA = [
 {id:'animal', b:'1', t:{es:'Los bovinos de carne en México',en:'Beef cattle in Mexico'}, h:{
  es:`<p>México produce cerca de 2.2 millones de toneladas de carne de bovino en canal al año (SIAP, 2024). Conviven tres mundos: el <b>vaca-becerro</b> en agostaderos del norte y en praderas del trópico, el <b>doble propósito</b> del Golfo y el Pacífico, y la <b>engorda intensiva</b> en corral, concentrada en Sinaloa, Sonora, Jalisco, Durango y Veracruz. Los becerros nacen en el trópico y en el norte, y muchos se terminan en los corrales del noroeste y del occidente.</p><p>El biotipo pesa: el <b>cebú</b> (Brahman, Nelore, Gyr, Guzerat, Indubrasil, Sardo Negro) gasta 10 % menos en mantenimiento y tolera el calor; las <b>cruzas</b> F1 combinan rusticidad y crecimiento; los <b>europeos</b> crecen más rápido pero sufren el calor; los machos <b>Holstein</b> de las cuencas lecheras requieren 20 % más de mantenimiento (NRC, 1996).</p>`,
  en:`<p>Mexico produces about 2.2 million tonnes of carcass beef a year (SIAP, 2024). Three worlds coexist: <b>cow–calf</b> on northern rangeland and tropical pastures, <b>dual purpose</b> on the Gulf and Pacific, and <b>intensive feedlots</b> concentrated in Sinaloa, Sonora, Jalisco, Durango and Veracruz. Calves are born in the tropics and the north, and many are finished in northwestern and western feedlots.</p><p>Biotype matters: <b>zebu</b> (Brahman, Nellore, Gyr, Guzerat, Indubrasil, Sardo Negro) spends 10 % less on maintenance and tolerates heat; F1 <b>crosses</b> combine hardiness and growth; <b>Europeans</b> grow faster but suffer in the heat; dairy-basin <b>Holstein</b> males need 20 % more maintenance (NRC, 1996).</p>`}},
 {id:'sistemaEN', b:'1', t:{es:'El sistema de energía neta de California',en:'The California net energy system'}, h:{
  es:`<p>Lofgreen y Garrett (1968) separaron la energía del alimento en dos usos con eficiencias distintas: <b>ENm</b> (mantener el cuerpo) y <b>ENg</b> (formar tejido). El mantenimiento vale 0.077 Mcal por kg de peso metabólico (PVV⁰·⁷⁵) y la energía retenida, <i>ER = 0.0635 · PVVE⁰·⁷⁵ · GPV¹·⁰⁹⁷</i> (NASEM, 2016), depende del <b>peso equivalente</b>: un animal cerca de su peso de engrasamiento deposita más grasa y necesita más energía por kilo.</p><div class="idea"><b>Idea clave</b>La ENg que debe tener la ración depende de cuánto alimento se va en mantenimiento, y eso depende de la ENm de la misma ración: por eso RatioBos itera hasta que todo cuadra.</div>`,
  en:`<p>Lofgreen and Garrett (1968) split feed energy into two uses with different efficiencies: <b>NEm</b> (maintaining the body) and <b>NEg</b> (building tissue). Maintenance is 0.077 Mcal per kg of metabolic weight (SBW⁰·⁷⁵) and retained energy, <i>RE = 0.0635 · EQEBW⁰·⁷⁵ · EBG¹·⁰⁹⁷</i> (NASEM, 2016), depends on <b>equivalent weight</b>: an animal near its finishing weight deposits more fat and needs more energy per kilo.</p><div class="idea"><b>Key idea</b>The NEg the ration needs depends on how much feed goes to maintenance, which depends on the ration’s own NEm: that is why RatioBos iterates until everything matches.</div>`}},
 {id:'region', b:'2', t:{es:'Regiones, clima y suelos de México',en:'Regions, climate and soils of Mexico'}, h:{
  es:`<p>RatioBos agrupa los 32 estados en nueve regiones ganaderas con clima, suelos, razas, sistemas e insumos parecidos. En el <b>noroeste</b> el reto es el calor seco extremo; en el <b>norte</b>, el frío invernal y la sequía; en el <b>Golfo</b> y la <b>Península</b>, el calor húmedo, el lodo y los suelos ácidos o kársticos pobres en fósforo; en el <b>altiplano</b>, las heladas y el flete del grano.</p><p>La región cambia tres cosas del modelo: el <b>ambiente</b> (temperatura, humedad, aclimatación y lodo), los <b>precios</b> de los ingredientes y los factores de <b>estiércol</b> (lixiviación en climas húmedos). La infraestructura atenúa el ambiente: la sombra y los pisos con drenaje recuperan ganancia que el clima quita.</p>`,
  en:`<p>RatioBos groups the 32 states into nine cattle regions with similar climate, soils, breeds, systems and feeds. In the <b>northwest</b> the challenge is extreme dry heat; in the <b>north</b>, winter cold and drought; on the <b>Gulf</b> and the <b>Peninsula</b>, humid heat, mud and acid or karst soils low in phosphorus; in the <b>highlands</b>, frost and grain freight.</p><p>The region changes three things in the model: the <b>environment</b> (temperature, humidity, acclimation and mud), ingredient <b>prices</b> and <b>manure</b> factors (leaching in humid climates). Infrastructure softens the environment: shade and drained floors recover gain that climate takes away.</p>`}},
 {id:'ith', b:'2', t:{es:'Índice de temperatura y humedad (ITH)',en:'Temperature–humidity index (THI)'}, h:{
  es:`<p><i>ITH = 0.81·T + (HR/100)·(T − 14.4) + 46.4</i>. El ganado de engorda entra en estrés por calor desde ITH 75; de 75 a 78 es <b>alerta</b>, de 79 a 83 <b>peligro</b> y 84 o más <b>emergencia</b>. En una engorda comercial de Culiacán, con ITH de 77 a 83, la sombra tipo domo con ventiladores bajó el consumo y mejoró la eficiencia alimenticia de toros cebú sin reducir la ganancia (Avendaño-Reyes et al., 2025).</p><p>RatioBos descuenta del ITH lo que alivia la sombra (2 a 6 unidades) y la adaptación del biotipo (cebú 3, cruzas 1.5) y traduce el resultado en jadeo, que eleva el mantenimiento 7 % o 18 % (NRC, 1996). Son ajustes prácticos aproximados: si observas jadeo, captúralo directamente.</p>`,
  en:`<p><i>THI = 0.81·T + (RH/100)·(T − 14.4) + 46.4</i>. Feedlot cattle are heat-stressed from THI 75; 75–78 is <b>alert</b>, 79–83 <b>danger</b> and 84 or more <b>emergency</b>. In a commercial feedlot in Culiacán with THI 77–83, a dome shade with fans lowered intake and improved feed efficiency of zebu bulls without reducing gain (Avendaño-Reyes et al., 2025).</p><p>RatioBos subtracts from THI what shade relieves (2 to 6 units) and biotype adaptation (zebu 3, crosses 1.5) and turns the result into panting, which raises maintenance 7 % or 18 % (NRC, 1996). These are approximate practical adjustments: if you see panting, enter it directly.</p>`}},
 {id:'infra', b:'2', t:{es:'Infraestructura y ganancia de peso',en:'Infrastructure and weight gain'}, h:{
  es:`<ul><li><b>Sombra:</b> 2.5–4 m² por animal en clima cálido; la de lámina convencional (1.3 m²) alivia poco.</li><li><b>Piso y drenaje:</b> cada centímetro de lodo baja ≈ 1 % el consumo; pendiente de 3–5 % y montículos.</li><li><b>Comedero y agua:</b> 30–45 cm de comedero por animal en finalización, agua limpia a libre acceso.</li><li><b>Pastoreo:</b> caminar y buscar forraje elevan el mantenimiento 10 % en terreno plano y 20 % en lomerío (NRC, 1996).</li></ul>`,
  en:`<ul><li><b>Shade:</b> 2.5–4 m² per head in hot climates; conventional sheet metal (1.3 m²) helps little.</li><li><b>Floor and drainage:</b> each centimeter of mud cuts intake ≈ 1 %; 3–5 % slope and mounds.</li><li><b>Bunk and water:</b> 30–45 cm of bunk per head in finishing, clean water freely available.</li><li><b>Grazing:</b> walking and foraging raise maintenance 10 % on flat land and 20 % on hills (NRC, 1996).</li></ul>`}},
 {id:'regional', b:'2', t:{es:'Lo que enseña la investigación regional',en:'What regional research teaches'}, h:{
  es:`<ul><li><b>Sonora (CIPES):</b> en agostadero de zacate buffel las vaquillas ganan 0.19 kg/d sin suplemento y 0.62–0.67 kg/d con suplemento proteico en la seca; la proteína de buena calidad subió la fertilidad al primer empadre de 55 a 87 %. En corral, las dietas con 45 % de melaza llegaron a 1.27 kg/d cuando llevaron 5 % de proteína sobrepasante, y los implantes aumentaron 15–20 % la ganancia (Gómez-Alarcón et al., 1989). Un forraje barato, como el esquilmo de algodón con pasta de cártamo, dio igual ganancia que la alfalfa y más utilidad (Zambrano y Salcedo, 1973).</li><li><b>Sinaloa:</b> en 1,560 toretes con ITH medio de 80.9, la sombra total con ventilador elevó la ganancia de 1.15 a 1.32 kg/d (Castro-Pérez et al., 2020); los domos con ventiladores dejaron 29.66 USD más por animal y redujeron 3–8 % los GEI y el amoniaco por kg de carne (Mejía-Turcios et al., 2024).</li><li><b>Chihuahua:</b> en agostadero de bajos insumos, las vacas Angus × Criollo Rarámuri destetaron más kilos por kg de vaca (Floriano-López et al., 2024).</li><li><b>Zacatecas:</b> becerros de alto riesgo ganaron 1.22–1.42 kg/d en recepción con 50 % de forraje (Rodríguez-Cordero et al., 2025).</li><li><b>Veracruz:</b> los toros Criollo Lechero Tropical respondieron con más ganancia y mejor canal a una dieta de 2.9 Mcal EM/kg que a una de 2.2 (Sánchez-Arroyo et al., 2023).</li><li><b>Frontera con Baja California:</b> el grupo de Zinn (UC Davis, Valle Imperial) documenta becerros Holstein de 1.3–1.4 kg/d con 7–25 % de DDGS (Carvalho et al., 2022; Montano et al., 2023; Salinas-Chavira et al., 2024).</li></ul>`,
  en:`<ul><li><b>Sonora (CIPES):</b> on buffelgrass rangeland heifers gain 0.19 kg/d unsupplemented and 0.62–0.67 kg/d with dry-season protein supplement; good-quality protein raised first-breeding fertility from 55 to 87 %. In pens, 45 % molasses diets reached 1.27 kg/d with 5 % bypass protein, and implants raised gain 15–20 % (Gómez-Alarcón et al., 1989). A cheap roughage such as cotton gin trash with safflower meal matched alfalfa’s gain at higher profit (Zambrano and Salcedo, 1973).</li><li><b>Sinaloa:</b> in 1,560 bulls at mean THI 80.9, total shade with a fan raised gain from 1.15 to 1.32 kg/d (Castro-Pérez et al., 2020); domes with fans returned 29.66 USD more per head and cut GHG and ammonia per kg of beef by 3–8 % (Mejía-Turcios et al., 2024).</li><li><b>Chihuahua:</b> on low-input rangeland, Angus × Rarámuri Criollo cows weaned the most kilos per kg of cow (Floriano-López et al., 2024).</li><li><b>Zacatecas:</b> high-risk calves gained 1.22–1.42 kg/d on a 50 % forage receiving diet (Rodríguez-Cordero et al., 2025).</li><li><b>Veracruz:</b> Tropical Milking Criollo bulls responded with more gain and better carcasses to a 2.9 Mcal ME/kg diet than to 2.2 (Sánchez-Arroyo et al., 2023).</li><li><b>Baja California border:</b> Zinn’s group (UC Davis, Imperial Valley) documents Holstein calves at 1.3–1.4 kg/d with 7–25 % DDGS (Carvalho et al., 2022; Montano et al., 2023; Salinas-Chavira et al., 2024).</li></ul>`}},
 {id:'requer', b:'3', t:{es:'Requerimientos por el método factorial',en:'Factorial requirements'}, h:{
  es:`<p>Cada requerimiento es la suma de sus usos: <b>mantenimiento + crecimiento + gestación + leche</b>. La proteína metabolizable de mantenimiento es 3.8 g/kg PVV⁰·⁷⁵; la de crecimiento, la proteína retenida <i>PR = GPV·(268 − 29.4·ER/GPV)</i> entre su eficiencia (0.834 − 0.00114·PVVE, mínimo 0.492). Para vacas, la gestación sigue curvas exponenciales del peso del becerro y los días (NRC, 1996) y la leche se calcula con su grasa y proteína. Calcio y fósforo se suman igual y se dividen entre su absorción (50 % y 68 %).</p><p>El <b>consumo</b> se predice con NRC (1996) y NASEM (2016) a partir del peso y la ENm de la dieta, con ajustes por raza, engrasamiento, implante, ionóforo, temperatura y lodo. Para el cebú puede consultarse además el BR-CORTE (Valadares Filho et al., 2023).</p>`,
  en:`<p>Each requirement is the sum of its uses: <b>maintenance + growth + pregnancy + milk</b>. Maintenance metabolizable protein is 3.8 g/kg SBW⁰·⁷⁵; growth is retained protein <i>RP = SWG·(268 − 29.4·RE/SWG)</i> divided by its efficiency (0.834 − 0.00114·EQSBW, minimum 0.492). For cows, pregnancy follows exponential curves of calf weight and days (NRC, 1996) and milk is computed from its fat and protein. Calcium and phosphorus are summed the same way and divided by absorption (50 % and 68 %).</p><p><b>Intake</b> is predicted with NRC (1996) and NASEM (2016) from weight and dietary NEm, adjusted for breed, fatness, implant, ionophore, temperature and mud. For zebu, BR-CORTE (Valadares Filho et al., 2023) can also be consulted.</p>`}},
 {id:'energia', b:'3', t:{es:'Energía: TND, EM, ENm y ENg',en:'Energy: TDN, ME, NEm and NEg'}, h:{
  es:`<p>Los alimentos se describen por su TND; la energía metabolizable es 0.82 × la digestible (4.409 Mcal por kg de TND). La ENm y la ENg de cada ingrediente vienen de la tabla y se suman en proporción a su inclusión, como en los artículos de referencia. El maíz <b>hojueleado al vapor</b> rinde ≈ 15 % más ENg que el rolado; los <b>ionóforos</b> aumentan ≈ 12 % el valor de ENm de la dieta.</p>`,
  en:`<p>Feeds are described by their TDN; metabolizable energy is 0.82 × digestible energy (4.409 Mcal per kg TDN). Each ingredient’s NEm and NEg come from the table and add up in proportion to inclusion, as in the reference papers. <b>Steam-flaked</b> corn yields ≈ 15 % more NEg than dry-rolled; <b>ionophores</b> raise the diet’s NEm value by ≈ 12 %.</p>`}},
 {id:'proteina', b:'3', t:{es:'Proteína degradable, microbiana y metabolizable',en:'Degradable, microbial and metabolizable protein'}, h:{
  es:`<p>Los microbios del rumen sintetizan proteína con la energía que fermentan: <i>PCM (g/d) = 42.73 + 0.087 · TND consumido (g/d)</i> (Galyean y Tedeschi, 2014; NASEM, 2016), si tienen proteína degradable suficiente. La proteína metabolizable es 64 % de la microbiana más 80 % de la que escapa al rumen. RatioBos exige un <b>balance de PDR ≥ 0</b>: si falta nitrógeno, la urea o una pasta lo corrigen al menor costo.</p>`,
  en:`<p>Rumen microbes synthesize protein from the energy they ferment: <i>MCP (g/d) = 42.73 + 0.087 · TDN intake (g/d)</i> (Galyean and Tedeschi, 2014; NASEM, 2016), provided degradable protein is sufficient. Metabolizable protein is 64 % of microbial protein plus 80 % of rumen-escape protein. RatioBos requires an <b>RDP balance ≥ 0</b>: if nitrogen is short, urea or a meal fixes it at the lowest cost.</p>`}},
 {id:'minerales', b:'3', t:{es:'Minerales, fibra efectiva y salud ruminal',en:'Minerals, effective fiber and rumen health'}, h:{
  es:`<p>Las raciones de engorda tienen poco forraje: en Brasil el promedio es 15.7 % (10–25 %) de la MS (Monsalve y Millen, 2025). La <b>fibra físicamente efectiva</b> mantiene la rumia y el pH; sin ella aparecen acidosis, timpanismo y abscesos hepáticos. El <b>azufre</b> total (alimento + agua) por encima de 0.30 % en dietas de grano causa polioencefalomalacia: RatioBos descuenta el que trae el agua. Con grano sobra fósforo y hay que agregar calcio (Ca:P ≥ 1.5).</p>`,
  en:`<p>Feedlot rations carry little forage: the Brazilian average is 15.7 % (10–25 %) of DM (Monsalve and Millen, 2025). <b>Physically effective fiber</b> keeps rumination and pH up; without it come acidosis, bloat and liver abscesses. Total <b>sulfur</b> (feed + water) above 0.30 % in grain diets causes polioencephalomalacia: RatioBos deducts what water brings. Grain diets carry surplus phosphorus and need added calcium (Ca:P ≥ 1.5).</p>`}},
 {id:'aditivos', b:'4', t:{es:'Ionóforos, implantes, β-agonistas y antibióticos',en:'Ionophores, implants, β-agonists and antibiotics'}, h:{
  es:`<p>La <b>monensina</b> es el aditivo más usado en las engordas (70 % de los nutriólogos en Brasil; Monsalve y Millen, 2025) y no tiene importancia médica humana. Los <b>implantes</b> aumentan ganancia y consumo; los <b>β-agonistas</b> autorizados (zilpaterol, ractopamina) se usan al final con retiro obligatorio; el clenbuterol está prohibido. Los antibióticos en el alimento (tilosina, virginiamicina) pertenecen a clases de importancia médica para la OMS: su uso debe justificarse y reducirse.</p>`,
  en:`<p><b>Monensin</b> is the most used feedlot additive (70 % of nutritionists in Brazil; Monsalve and Millen, 2025) and has no human medical importance. <b>Implants</b> raise gain and intake; authorized <b>β-agonists</b> (zilpaterol, ractopamine) are used at the end with mandatory withdrawal; clenbuterol is banned. In-feed antibiotics (tylosin, virginiamycin) belong to WHO medically important classes: their use should be justified and reduced.</p>`}},
 {id:'economia', b:'4', t:{es:'Indicadores económicos',en:'Economic indicators'}, h:{
  es:`<ul><li><b>Costo por kg ganado</b> = costo diario ÷ GDP: el criterio para elegir ración.</li><li><b>Eficiencia alimenticia</b> = GDP ÷ CMS; <b>conversión</b> = CMS ÷ GDP.</li><li><b>Relación beneficio : costo</b> = ingresos ÷ costos; mayor que 1 deja utilidad.</li><li><b>Precio de equilibrio</b> = (compra + alimento + otros) ÷ peso de venta.</li></ul>`,
  en:`<ul><li><b>Cost per kg gained</b> = daily cost ÷ ADG: the criterion for choosing a ration.</li><li><b>Feed efficiency</b> = ADG ÷ DMI; <b>conversion</b> = DMI ÷ ADG.</li><li><b>Benefit : cost ratio</b> = revenue ÷ costs; above 1 it is profitable.</li><li><b>Break-even price</b> = (purchase + feed + other) ÷ sale weight.</li></ul>`}},
 {id:'ingredientes', b:'5', t:{es:'La matriz de ingredientes en base seca',en:'The dry-basis ingredient matrix'}, h:{
  es:`<p>En rumiantes se formula en <b>materia seca</b>: un ensilaje con 34 % de MS y un grano con 88 % no se comparan por kg húmedo. Los valores de RatioBos vienen de la tabla de Beck, Lalman y Moehlenpah (2024), que reúne NASEM (2016), laboratorios comerciales y ensayos. Cada alimento trae además su factor de fibra efectiva y la fracción degradable de su proteína.</p><div class="idea"><b>Idea clave</b>Las tablas son promedios. Analiza tus forrajes y ensilajes (MS, PC, FDN): es lo que más mejora una ración.</div>`,
  en:`<p>Ruminants are formulated on <b>dry matter</b>: a 34 % DM silage and an 88 % DM grain cannot be compared per wet kg. RatioBos values come from Beck, Lalman and Moehlenpah (2024), which compiles NASEM (2016), commercial laboratories and trials. Each feed also carries its effective-fiber factor and its protein’s degradable fraction.</p><div class="idea"><b>Key idea</b>Tables are averages. Analyze your forages and silages (DM, CP, NDF): it improves a ration more than anything else.</div>`}},
 {id:'limites', b:'6', t:{es:'Precios y límites de inclusión',en:'Prices and inclusion limits'}, h:{
  es:`<p>El modelo minimiza el costo por kg de <b>materia seca</b>, así que el precio húmedo se divide entre la MS. En 2026 el sorgo se pagó al productor en 3,600–3,800 $/t en Tamaulipas y el maíz amarillo cerca de 4,000 $/t; con flete y proceso cuestan más en el rancho. Los límites prácticos: urea ≤ 1 %, grasa añadida ≤ 3–4 %, semilla de algodón ≤ 15 %, DDGS ≤ 30 % (azufre y grasa), melaza ≤ 10 % en engorda.</p>`,
  en:`<p>The model minimizes cost per kg of <b>dry matter</b>, so the wet price is divided by DM. In 2026 sorghum paid producers 3,600–3,800 $/t in Tamaulipas and yellow corn about 4,000 $/t; with freight and processing they cost more at the ranch. Practical limits: urea ≤ 1 %, added fat ≤ 3–4 %, whole cottonseed ≤ 15 %, DDGS ≤ 30 % (sulfur and fat), molasses ≤ 10 % in finishing.</p>`}},
 {id:'lp', b:'7', t:{es:'Programación lineal de mínimo costo',en:'Least-cost linear programming'}, h:{
  es:`<p>Formular es encontrar la proporción de cada ingrediente que <b>minimiza el costo</b> cumpliendo cada nutriente por kg de MS, los límites de inclusión y la suma de 100 % (Dantzig, 1963). RatioBos usa el símplex en dos fases con la regla de Bland y comprueba la optimalidad por dualidad fuerte.</p>`,
  en:`<p>Formulating means finding the proportion of each ingredient that <b>minimizes cost</b> while meeting each nutrient per kg DM, inclusion limits and a 100 % sum (Dantzig, 1963). RatioBos uses two-phase simplex with Bland’s rule and checks optimality by strong duality.</p>`}},
 {id:'iterativo', b:'7', t:{es:'Ajuste iterativo de energía y consumo',en:'Iterative energy and intake adjustment'}, h:{
  es:`<p>1) Se supone una ENm de la dieta; 2) con ella se predice el consumo y la ENg necesaria; 3) se resuelve el modelo lineal; 4) se toma la ENm de la ración obtenida y se repite con amortiguamiento hasta que el cambio es menor que 0.002 Mcal/kg. Así la ración y el consumo quedan coherentes con las ecuaciones del animal.</p>`,
  en:`<p>1) A dietary NEm is assumed; 2) intake and required NEg are predicted from it; 3) the linear model is solved; 4) the resulting ration’s NEm is taken and the loop repeats with damping until the change is below 0.002 Mcal/kg. Ration and intake thus become consistent with the animal equations.</p>`}},
 {id:'lectura', b:'7', t:{es:'Cómo leer el resultado',en:'Reading the result'}, h:{
  es:`<p><b>Limitante:</b> el nutriente o límite que queda justo en su mínimo o máximo. <b>Precio sombra:</b> cuánto cambia el costo si ese requerimiento sube. <b>Precio de entrada:</b> a qué precio convendría un ingrediente no usado. <b>Ganancia permitida:</b> la menor entre la que permite la energía y la proteína metabolizable.</p>`,
  en:`<p><b>Binding:</b> the nutrient or limit sitting exactly at its minimum or maximum. <b>Shadow price:</b> how much cost changes if that requirement rises. <b>Entry price:</b> at what price an unused ingredient would pay. <b>Allowable gain:</b> the lower of energy- and metabolizable-protein-allowable gain.</p>`}},
 {id:'programa', b:'8', t:{es:'Programas de engorda y ciclo de la vaca',en:'Feedlot programs and the cow cycle'}, h:{
  es:`<p>Una engorda típica tiene <b>recepción y adaptación</b> (más forraje, 2–3 semanas para que el rumen se acostumbre al grano), <b>crecimiento</b> y <b>finalización</b>. En el sur y centro del país las engordas duran 70–90 días y en el norte más de 120 (Martínez, 2023). RatioBos simula el crecimiento día a día con la ganancia que permite cada ración y el consumo a cada peso. Para la vaca de cría, el año se divide en gestación media, gestación final, lactación temprana y tardía.</p>`,
  en:`<p>A typical feedlot program has <b>receiving and step-up</b> (more forage, 2–3 weeks for the rumen to adapt to grain), <b>growing</b> and <b>finishing</b>. In southern and central Mexico feedlots last 70–90 days and in the north over 120 (Martínez, 2023). RatioBos simulates growth day by day with each ration’s allowable gain and the intake at each weight. For the beef cow, the year is split into mid and late gestation and early and late lactation.</p>`}},
 {id:'indicadores', b:'9', t:{es:'La ganancia económicamente óptima',en:'The economically optimal gain'}, h:{
  es:`<p>La ganancia más alta no siempre es la más rentable: cada kilo extra exige una ración más cara. El tablero formula raciones para varias metas y calcula el margen diario (valor de la ganancia − alimento − otros costos); la meta con el mayor margen es la <b>ganancia económicamente óptima</b>. También compara el mismo animal en las nueve regiones y mide la sensibilidad al precio del grano.</p>`,
  en:`<p>The highest gain is not always the most profitable: each extra kilo needs a costlier ration. The dashboard formulates rations for several targets and computes the daily margin (value of gain − feed − other costs); the target with the highest margin is the <b>economically optimal gain</b>. It also compares the same animal across the nine regions and measures sensitivity to the grain price.</p>`}},
 {id:'sostenible', b:'10', t:{es:'Sostenibilidad según la FAO',en:'Sustainability as defined by FAO'}, h:{
  es:`<p>Para la FAO, la <b>sostenibilidad</b> de la alimentación y la agricultura descansa en cuatro dimensiones —integridad ambiental, resiliencia económica, bienestar social y buena gobernanza— según su marco SAFA (FAO, 2014), y exige producir más con menos recursos y menos externalidades (FAO, 2018). RatioBos mide la dimensión ambiental de la ración —agua, suelo, gases, nitrógeno, fósforo, estiércol y medicamentos— junto con la económica, y permite formular con un <b>precio interno del carbono</b> para buscar el equilibrio entre utilidad y carga ambiental.</p>`,
  en:`<p>For FAO, the <b>sustainability</b> of food and agriculture rests on four dimensions — environmental integrity, economic resilience, social well-being and good governance — under its SAFA framework (FAO, 2014), and requires producing more with fewer resources and fewer externalities (FAO, 2018). RatioBos measures the ration’s environmental dimension — water, land, gases, nitrogen, phosphorus, manure and medicines — alongside the economic one, and lets you formulate with an <b>internal carbon price</b> to find the balance between profit and environmental load.</p>`}},
 {id:'gei', b:'10', t:{es:'Cómo se calculan los gases y los nutrientes',en:'How gases and nutrients are computed'}, h:{
  es:`<ul><li><b>Metano entérico:</b> energía bruta (18.45 MJ/kg MS) × Ym; Ym de 3 % para concentrados y 4–7 % para forrajes según su digestibilidad, ponderado por la ración (IPCC, 2019).</li><li><b>Metano del estiércol:</b> sólidos volátiles × 0.18 m³/kg × 0.67 × MCF (1–2 % en corral, 0.47 % en pastoreo).</li><li><b>Óxido nitroso:</b> directo (2 % del N en corral, 0.4 % en pastoreo) e indirecto por volatilización (1 %) y lixiviación (1.1 % del 24 % lixiviado en climas húmedos).</li><li><b>Equivalentes de CO₂:</b> CH₄ × 27 y N₂O × 273 (IPCC, AR6).</li><li><b>Agua y suelo:</b> factores por ingrediente de huella hídrica (Mekonnen y Hoekstra, 2011) y rendimientos medios; editables.</li><li><b>Superficie para estiércol:</b> 170 kg N/ha·año o 25 kg P/ha·año; <b>agua gris</b>: volumen para diluir el N lixiviado a 10 mg/L.</li></ul>`,
  en:`<ul><li><b>Enteric methane:</b> gross energy (18.45 MJ/kg DM) × Ym; Ym of 3 % for concentrates and 4–7 % for forages by digestibility, weighted by the ration (IPCC, 2019).</li><li><b>Manure methane:</b> volatile solids × 0.18 m³/kg × 0.67 × MCF (1–2 % in drylots, 0.47 % on pasture).</li><li><b>Nitrous oxide:</b> direct (2 % of N in drylots, 0.4 % on pasture) and indirect via volatilization (1 %) and leaching (1.1 % of the 24 % leached in humid climates).</li><li><b>CO₂ equivalents:</b> CH₄ × 27 and N₂O × 273 (IPCC, AR6).</li><li><b>Water and land:</b> per-ingredient water-footprint factors (Mekonnen and Hoekstra, 2011) and average yields; editable.</li><li><b>Manure land:</b> 170 kg N/ha·yr or 25 kg P/ha·yr; <b>grey water</b>: volume to dilute leached N to 10 mg/L.</li></ul>`}},
 {id:'modernas', b:'', t:{es:'Otras herramientas de formulación para bovinos',en:'Other beef formulation tools'}, h:{
  es:`<p>RatioBos se inspira en la familia de modelos de NASEM: el <b>BCNRM</b> (NASEM, 2016) y el <b>Ruminant Nutrition System</b> (Tedeschi y Fox, 2020), herederos del CNCPS de Cornell; en el <b>BR-CORTE</b> para cebú y sus cruzas (Valadares Filho et al., 2023); y en las calculadoras de cierre de corral de las universidades estadounidenses. Su aporte propio: todo en el navegador, en español e inglés, ajustado a las regiones de México, con validación publicada y con huella ambiental y económica en la misma pantalla.</p>`,
  en:`<p>RatioBos draws on the NASEM model family: the <b>BCNRM</b> (NASEM, 2016) and the <b>Ruminant Nutrition System</b> (Tedeschi and Fox, 2020), heirs of Cornell’s CNCPS; on <b>BR-CORTE</b> for zebu and crosses (Valadares Filho et al., 2023); and on US university feedlot close-out calculators. Its own contribution: everything in the browser, in Spanish and English, adjusted to Mexico’s regions, with published validation and environmental and economic footprints on the same screen.</p>`}},
 {id:'validacion', b:'✓', t:{es:'¿Cómo se valida un formulador?',en:'How is a formulation tool validated?'}, h:{
  es:`<ol><li><b>Aporte:</b> capturar dietas publicadas y comparar el análisis calculado.</li><li><b>Energética:</b> repetir el cálculo de energía neta observada (Zinn y Shen, 1998) con el desempeño medido.</li><li><b>Optimización:</b> reformular con el mismo aporte; debe salir igual o más barata.</li><li><b>Matemática:</b> comparar con un solucionador independiente.</li></ol><p>Diferencias de ±3–5 % en energía y proteína son normales entre tablas de alimentos.</p>`,
  en:`<ol><li><b>Supply:</b> enter published diets and compare the calculated analysis.</li><li><b>Energetics:</b> repeat the observed net-energy calculation (Zinn and Shen, 1998) with measured performance.</li><li><b>Optimization:</b> reformulate with the same supply; it must come out equal or cheaper.</li><li><b>Mathematics:</b> compare with an independent solver.</li></ol><p>Differences of ±3–5 % in energy and protein are normal between feed tables.</p>`}}
];
const CONSEJO = {
  animal:{es:'Elige qué animales vas a alimentar, su raza y si son toretes, novillos o vaquillas. Con eso la app sabe cuánto gastan y cuánto pueden ganar.',en:'Choose which animals you will feed, their breed and whether they are bulls, steers or heifers. The app then knows how much they spend and can gain.'},
  region:{es:'Toca tu estado en el mapa y la temporada del año. La app pone el clima, te dice si hay estrés por calor y te ajusta los precios a tu región.',en:'Tap your state on the map and the season. The app sets the climate, tells you about heat stress and adjusts prices to your region.'},
  requer:{es:'Escribe el peso de tus animales y cuánto quieres que ganen al día (o los días de preñez o la leche de tus vacas). La app calcula lo que necesitan.',en:'Enter your animals’ weight and how much you want them to gain per day (or days pregnant or milk for cows). The app computes what they need.'},
  aditivos:{es:'Marca si usas implante e ionóforo, cuántos animales tienes, los medicamentos y a cómo compras y vendes el kilo en pie.',en:'Tick whether you use an implant and ionophore, how many head you have, the medicines and your purchase and sale price per live kilo.'},
  ingredientes:{es:'Marca solo lo que puedes conseguir en tu región. Mientras más opciones, más barata puede salir la ración.',en:'Tick only what you can get in your region. The more options, the cheaper the ration can be.'},
  limites:{es:'Escribe el precio que pagas puesto en tu rancho, tal como lo compras. La app lo pasa a materia seca.',en:'Enter the price you pay delivered to your ranch, as you buy it. The app converts it to dry matter.'},
  lp:{es:'Presiona Formular: la app busca la ración más barata que cubre lo que necesita tu ganado y te da la hoja de mezclado para el carro.',en:'Press Formulate: the app finds the cheapest ration that covers your cattle’s needs and gives you the mixer sheet.'},
  programa:{es:'Simula toda la engorda: cuántos días tarda, cuánto alimento y dinero se va y cuánto te queda por cabeza.',en:'Simulate the whole feeding period: how many days, how much feed and money it takes and what you keep per head.'},
  indicadores:{es:'Aquí ves todo en gráficas: ganancia, eficiencia, conversión, beneficio : costo, la ganancia que deja más dinero y cómo cambia el costo entre regiones.',en:'Here you see everything in charts: gain, efficiency, conversion, benefit : cost, the gain that makes the most money and how cost changes across regions.'},
  sostenible:{es:'Mira cuánta agua, suelo y gases cuesta tu ración, y busca una que cuide el ambiente sin dejar de ser rentable.',en:'See how much water, land and gas your ration costs, and look for one that cares for the environment while staying profitable.'},
  validacion:{es:'RatioBos se comparó con dietas de engorda publicadas por investigadores mexicanos y de la Universidad de California, y dio resultados muy parecidos.',en:'RatioBos was checked against feedlot diets published by Mexican and University of California researchers, with very similar results.'}
};
function teoriaDe(ids){
  const c = CONSEJO[ids[0]];
  return `${c?`<div class="consejo prod">${ill('i-prod')}<div><div class="k">${T('En pocas palabras','In a nutshell')}</div><p>${esc(tx(c))}</p></div></div>`:''}` + teoriaSci(ids);
}
function teoriaSci(ids){
  const items = TEORIA.filter(t=>ids.includes(t.id)); if(!items.length) return '';
  return `<section class="teoria sci"><div class="th"><div><h2>${T('Marco teórico','Theoretical framework')}</h2><p>${T('Lo que conviene tener claro antes de decidir. Despliega la sección que necesites.','What to keep in mind before deciding. Open the section you need.')}</p></div><button class="btn ghost sm" data-ir="teoria">${T('Ver todo','See all')}</button></div>
    ${items.map(t=>`<details><summary>${TEORIA.indexOf(t)+1} · ${esc(tx(t.t))}</summary><div class="tb">${tx(t.h)}</div></details>`).join('')}</section>`;
}
const REFERENCIAS = [
  'Avendaño-Reyes, L., Macías-Cruz, U., Vicente-Pérez, A., Aguilar, J. A., López-Baca, M. Á., Roque-Jiménez, J. A., Mellado, M., Gastelum, M. Á., & Siller, J. A. (2025). Toros <i>Bos indicus</i> engordados bajo estrés por calor en corrales provisto de sombra tipo domo: respuestas fisiológicas y productivas. <i>Revista Mexicana de Ciencias Pecuarias, 16</i>(3), 537–554. https://doi.org/10.22319/rmcp.v16i3.6859',
  'Beck, P., Lalman, D., & Moehlenpah, A. (2024). <i>Nutritive value of feeds</i> (ANSI-3018). Oklahoma State University Extension.',
  'Carvalho, P. H. V., Latack, B. C., Flores, R., Montano, M. F., & Zinn, R. A. (2022). Interaction of early metabolizable protein supplementation and virginiamycin on feedlot growth performance and carcass characteristics of calf-fed Holstein steers. <i>Translational Animal Science, 6</i>(1), txab228. https://doi.org/10.1093/tas/txab228',
  'Castro-Pérez, B. I., Estrada-Angulo, A., Ríos-Rincón, F. G., Núñez-Benítez, V. H., Rivera-Méndez, C. R., Urías-Estrada, J. D., Zinn, R. A., Barreras, A., & Plascencia, A. (2020). The influence of shade allocation or total shade plus overhead fan on growth performance, efficiency of dietary energy utilization, and carcass characteristics of feedlot cattle under tropical ambient conditions. <i>Asian-Australasian Journal of Animal Sciences, 33</i>(6), 1034. https://doi.org/10.5713/ajas.19.0112',
  'Floriano-López, A., Rodríguez-Almeida, F. A., Martínez-Quintana, J. A. A., Sandoval-Villalobos, J., Roacho-Estrada, O., Villarreal-Balderrama, J., & Antillón-Ruiz, J. (2024). Productive performance of Raramuri Criollo, Angus × Raramuri Criollo and Hereford × Angus cows in a low-input cow-calf system in northern Mexico. <i>Journal of Animal Science, 102</i>(Suppl. 3), 456–457. https://doi.org/10.1093/jas/skae234.516',
  'Gómez-Alarcón, R., Limón-Navarro, J. E., & Arellanes-Ayala, J. (1989). <i>Nutrición animal: 20 años de investigación pecuaria en el CIPES</i>. Centro de Investigaciones Pecuarias del Estado de Sonora.',
  'González-Vizcarra, V. M., Plascencia, A., Ramos-Aviña, D., & Zinn, R. A. (2017). Influence of substituting steam-flaked corn for dry rolled corn on feedlot cattle growth performance when cattle are allowed either ad libitum or restricted access to the finishing diet. <i>Asian-Australasian Journal of Animal Sciences, 30</i>(11), 1563. https://doi.org/10.5713/ajas.17.0185',
  'Mejía-Turcios, S. E., Rotz, A., McGlone, J. J., Rivera, C., & Mitloehner, F. M. (2024). Effects of heat stress mitigation methods on growth performance, environmental, and economic outcomes of feedlot cattle raised in a hot climate. <i>Journal of Animal Science, 102</i>(Suppl. 3), 664–665. https://doi.org/10.1093/jas/skae234.754',
  'Montano, M. F., Carvalho, P. H. V., Ferraz Junior, M. V. C., Latack, B. C., & Zinn, R. A. (2023). Influence of level of dried distillers grains plus solubles substitution for steam-flaked corn on characteristics of growth performance, and dietary energetics of calf-fed Holstein steers during the initial 16-week growing phase. <i>Translational Animal Science, 7</i>(1), txad024. https://doi.org/10.1093/tas/txad024',
  'Rodríguez-Cordero, D., Carrillo-Muro, O., Hernández-Briano, P., Correa-Aguado, P. I., Rivera-Villegas, A., Barreras, A., Lazalde-Cruz, R., Zinn, R. A., & Plascencia, A. (2025). Optimal period of calcium propionate supplementation in arrival high-risk bull calves: Growth performance, body fat reserves, and serum metabolites. <i>Animals, 15</i>(8), 1170. https://doi.org/10.3390/ani15081170',
  'Salinas-Chavira, J., Carvalho, P. H. V., Latack, B. C., Ferraz Junior, M. V. C., Montano, M., & Zinn, R. A. (2024). Influence of metabolizable protein and methionine supplementation on growth-performance of Holstein steer calves during the initial 112-d feedlot growing phase. <i>Translational Animal Science, 8</i>, txae003. https://doi.org/10.1093/tas/txae003',
  'Sánchez-Arroyo, E., Vargas-Romero, J. M., Rosendo-Ponce, A., Hernández-Mendo, O., Pérez-Chabela, M. L., Pro-Martínez, A., & Becerril-Pérez, C. M. (2023). Growth performance, carcass, and meat quality traits of Tropical Milking criollo bulls fed with two energy-level diets. <i>Tropical Animal Health and Production, 55</i>, 62. https://doi.org/10.1007/s11250-023-03469-8',
  'Zambrano, R., & Salcedo, M. (1973). <i>Comparación de cuatro forrajes toscos en la engorda de vaquillas en corral</i> (F73003). Centro de Investigaciones Pecuarias del Estado de Sonora.',
  'Dantzig, G. B. (1963). <i>Linear programming and extensions</i>. Princeton University Press.',
  'Estrada-Angulo, A., Mendoza-Cortez, D. A., Ramos-Méndez, J. L., Arteaga-Wences, Y. J., Urías-Estrada, J. D., Castro-Pérez, B. I., Ríos-Rincón, F. G., Rodríguez-Gaxiola, M. A., Barreras, A., Zinn, R. A., & Plascencia, A. (2022). Comparing blend of essential oils plus 25-hydroxy-vit-D3 versus monensin plus virginiamycin combination in finishing feedlot cattle. <i>Animals, 12</i>(13), 1715. https://doi.org/10.3390/ani12131715',
  'FAO. (2014). <i>SAFA: Sustainability assessment of food and agriculture systems. Guidelines</i> (versión 3.0). Food and Agriculture Organization of the United Nations.',
  'FAO. (2018). <i>Transforming food and agriculture to achieve the SDGs: 20 interconnected actions to guide decision-makers</i>. Food and Agriculture Organization of the United Nations.',
  'Galyean, M. L., & Tedeschi, L. O. (2014). Predicting microbial protein synthesis in beef cattle: Relationship to intakes of total digestible nutrients and crude protein. <i>Journal of Animal Science, 92</i>(11), 5099–5111. https://doi.org/10.2527/jas.2014-8098',
  'IPCC. (2019). <i>2019 refinement to the 2006 IPCC guidelines for national greenhouse gas inventories</i>, vol. 4, cap. 10 y 11. Intergovernmental Panel on Climate Change.',
  'Lofgreen, G. P., & Garrett, W. N. (1968). A system for expressing net energy requirements and feed values for growing and finishing beef cattle. <i>Journal of Animal Science, 27</i>(3), 793–806.',
  'Martínez, E. D. (2023). Implicaciones que influyen en el desempeño productivo, características de la canal y de la carne de ganado bovino engordado en corral. <i>Revista de Investigaciones Veterinarias del Perú, 34</i>(3), e24517. https://doi.org/10.15381/rivep.v34i3.24517',
  'Mekonnen, M. M., & Hoekstra, A. Y. (2011). The green, blue and grey water footprint of crops and derived crop products. <i>Hydrology and Earth System Sciences, 15</i>, 1577–1600.',
  'Monsalve, J. G., & Millen, D. D. (2025). A snapshot of nutritional recommendations and management practices adopted by feedlot cattle nutritionists in Brazil in 2023. <i>Frontiers in Veterinary Science, 12</i>, 1518571. https://doi.org/10.3389/fvets.2025.1518571',
  'National Academies of Sciences, Engineering, and Medicine. (2016). <i>Nutrient requirements of beef cattle</i> (8th rev. ed.). The National Academies Press. https://doi.org/10.17226/19014',
  'National Research Council. (1996, 2000). <i>Nutrient requirements of beef cattle</i> (7th rev. ed.). National Academy Press.',
  'Plascencia, A., Latack, B. C., Carvalho, P. H. V., & Zinn, R. A. (2022). Feeding value of supplemental fat as a partial replacement for steam-flaked corn in diets for Holstein calves during the early growing phase. <i>Translational Animal Science, 6</i>(2), txac048. https://doi.org/10.1093/tas/txac048',
  'Ramos-Aviña, D., Plascencia, A., & Zinn, R. A. (2018). Influence of dietary nonstructural carbohydrate concentration on growth performance and carcass characteristics of Holstein steers. <i>Asian-Australasian Journal of Animal Sciences, 31</i>(6), 859–865. https://doi.org/10.5713/ajas.17.0425',
  'SIAP. (2024). <i>Panorama agroalimentario 2024</i>. Servicio de Información Agroalimentaria y Pesquera, SADER.',
  'Tedeschi, L. O., & Fox, D. G. (2020). <i>The ruminant nutrition system: Volume I – An applied model for predicting nutrient requirements and feed utilization in ruminants</i> (3rd ed.). XanEdu.',
  'Valadares Filho, S. C., et al. (2023). <i>BR-CORTE: Nutrient requirements of zebu and crossbred cattle</i> (4th ed.). Universidade Federal de Viçosa. https://doi.org/10.26626/978-85-8179-194-4.2023',
  'Zinn, R. A., & Shen, Y. (1998). An evaluation of ruminally degradable intake protein and metabolizable amino acid requirements of feedlot calves. <i>Journal of Animal Science, 76</i>(5), 1280–1289. https://doi.org/10.2527/1998.7651280x'
];
function renderTeoria(el){
  el.innerHTML = `${cabecera('teoria',T('Todo lo que conviene tener claro para formular bien. Cada sección indica el bloque donde se aplica.','Everything worth knowing to formulate well. Each section shows the block where it applies.'))}
  <section class="teoria"><div class="th"><div><h2>${T('Marco teórico de la formulación de raciones para bovinos de carne','Theoretical framework of beef cattle ration formulation')}</h2><p>${T('Despliega la sección que necesites.','Open the section you need.')}</p></div></div>
  ${TEORIA.map((t,i)=>`<details ${i===0?'open':''}><summary>${i+1} · ${esc(tx(t.t))} ${t.b?`<span class="badge">${T('Bloque','Block')} ${t.b}</span>`:''}</summary><div class="tb">${tx(t.h)}</div></details>`).join('')}</section>
  <div class="card small"><h3>${T('Referencias','References')}</h3><ul>${REFERENCIAS.slice().sort((a,b)=>a.localeCompare(b,'es')).map(r=>`<li>${r}</li>`).join('')}</ul></div>
  ${siguiente('teoria')}`;
}

/* =====================================================================
   9. NAVEGACIÓN, IDIOMA Y TEMA / NAVIGATION, LANGUAGE AND THEME
   ===================================================================== */
function renderNav(){
  $('#nav').innerHTML = BLOQUES.map(b=>`<button class="${S.bloque===b.id?'act':''} ${S.visitados[b.id]&&S.bloque!==b.id&&/^\d+$/.test(b.n)?'done':''}" data-ir="${b.id}"><span class="n">${b.n}</span>${esc(tx(b.corto))}</button>`).join('');
  const a = $('#nav .act'); if(a && a.scrollIntoView) a.scrollIntoView({block:'nearest',inline:'center'});
  const hechos = BLOQUES.filter(b=>/^\d+$/.test(b.n) && (S.visitados[b.id]||S.bloque===b.id)).length;
  $('#progTxt').textContent = T(`Avance: ${hechos} de ${NUMERADOS} bloques`,`Progress: ${hechos} of ${NUMERADOS} blocks`);
  $('#progFill').style.width = (100*hechos/NUMERADOS)+'%';
}
function actualizarPill(){
  const t = $('#pillTxt'); if(t) t.textContent = `${tx(CATEGORIAS[S.cat].n)} · ${tx(REGIONES[S.region].n)}` + (S.resultado&&S.resultado.ok?` · ${money(S.resultado.costoKgTCO*1000,0)}/t`:'');
}
function renderAyuda(){
  $('#dlgAyuda').innerHTML = `<div class="dh"><h2>${T('Cómo usar RatioBos','How to use RatioBos')}</h2><button class="ibtn round" onclick="this.closest('dialog').close()" aria-label="×">✕</button></div>
  <div class="db"><ol>
    <li>${T('<b>Avanza en orden</b> por los bloques: animal, región, requerimientos, manejo, ingredientes y precios.','<b>Move in order</b> through the blocks: animal, region, requirements, management, ingredients and prices.')}</li>
    <li>${T('En <b>Formulación</b> presiona <i>Formular</i>: se calcula la ración de mínimo costo y la ganancia que permite.','In <b>Formulation</b> press <i>Formulate</i>: the least-cost ration and the gain it allows are computed.')}</li>
    <li>${T('En <b>Programa</b> simulas toda la engorda o el ciclo de la vaca; en <b>Tablero</b> ves todo en gráficas; en <b>Sostenibilidad</b>, la huella ambiental.','In <b>Program</b> you simulate the whole feeding period or cow cycle; <b>Dashboard</b> shows everything in charts; <b>Sustainability</b> shows the environmental footprint.')}</li>
    <li>${T('El botón <b>Productor / Científico</b> cambia la vista; <b>ES / EN</b> cambia el idioma sin perder tus datos.','The <b>Producer / Scientist</b> button switches view; <b>ES / EN</b> switches language without losing your data.')}</li>
    <li>${T('Tu trabajo se <b>guarda solo</b> en este navegador. Para llevarlo a otra computadora usa <i>Informe → Guardar proyecto</i>.','Your work is <b>saved automatically</b> in this browser. To move it to another computer use <i>Report → Save project</i>.')}</li>
  </ol><p class="small muted">${T('Los valores precargados son de referencia. Revisa la ración con tu médico veterinario zootecnista o nutriólogo y analiza tus forrajes.','Preloaded values are references. Review the ration with your veterinarian or nutritionist and analyze your forages.')}</p></div>`;
}
function render(){
  document.documentElement.lang = LANG;
  $$('.langsw button[data-lang]').forEach(b=>b.classList.toggle('on', b.dataset.lang===LANG));
  document.documentElement.setAttribute('data-modo', MODO);
  $$('.modesw button').forEach(b=>{ const on=b.dataset.vista===MODO; b.classList.toggle('on',on); b.setAttribute('aria-pressed', on); });
  $('#lblProd').textContent = T('Productor','Producer'); $('#lblCien').textContent = T('Científico','Scientist');
  $('#modesw').title = T('Vista para productor o para científico','Producer or scientist view');
  $('#brandSub').textContent = T('· la razón al servicio del ganado','· reason in the service of cattle');
  const b = B(S.bloque) || BLOQUES[0];
  b.render()($('#main'));
  $('#pie').innerHTML = `<svg style="width:26px;height:26px;vertical-align:middle;margin-right:6px"><use href="#i-logo" width="100%" height="100%"/></svg><b>RatioBos</b> ${CONFIG.version} · ${T('Formulación de raciones para bovinos productores de carne','Beef cattle ration formulation')} · ${esc(CONFIG.autores)} · ${CONFIG.anio}<br><span class="tiny">${T('Herramienta de apoyo: los resultados deben ser revisados por un profesional en nutrición animal.','Decision-support tool: results should be reviewed by a qualified animal nutritionist.')} · MIT</span>`;
  renderNav(); actualizarPill(); renderAyuda();
}
function irA(id){ S.visitados[S.bloque]=true; S.bloque=id; guardar(); render(); window.scrollTo({top:0,behavior:'smooth'}); }
document.addEventListener('click',e=>{ const t=e.target.closest('[data-ir]'); if(t){ irA(t.dataset.ir); } });
function ponerModo(m){ MODO = m==='cien'?'cien':'prod'; try{ localStorage.setItem('ratiobos_modo',MODO); }catch(e){} render();
  toast(MODO==='cien'?T('Vista científica: modelo, iteraciones, validación y referencias','Scientist view: model, iterations, validation and references'):T('Vista productor: lo esencial, en lenguaje sencillo','Producer view: the essentials, in plain language')); }
document.addEventListener('click',e=>{ const t=e.target.closest('[data-vista]'); if(t){ ponerModo(t.dataset.vista); } });
$$('.langsw button[data-lang]').forEach(b=>b.addEventListener('click',()=>{ LANG=b.dataset.lang; try{ localStorage.setItem('ratiobos_lang',LANG); }catch(e){} render(); toast(LANG==='en'?'English':'Español'); }));
function aplicarTema(t){ if(t) document.documentElement.setAttribute('data-theme',t); else document.documentElement.removeAttribute('data-theme');
  const dark = t ? t==='dark' : matchMedia('(prefers-color-scheme: dark)').matches; $('#btnTema').textContent = dark?'☾':'☀'; }
$('#btnTema').addEventListener('click',()=>{ const cur = document.documentElement.getAttribute('data-theme') || (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
  const nt = cur==='dark'?'light':'dark'; aplicarTema(nt); try{ localStorage.setItem('ratiobos_tema',nt); }catch(e){} });
$('#btnAyuda').addEventListener('click',()=>{ const d=$('#dlgAyuda'); if(d.showModal) d.showModal(); });
try{ aplicarTema(localStorage.getItem('ratiobos_tema')); }catch(e){ aplicarTema(null); }
/* símbolo del mapa para la cabecera del Bloque 2, construido con los contornos */
(function(){ const sp = document.querySelector('svg defs'); if(!sp) return; const ns='http://www.w3.org/2000/svg';
  const sym = document.createElementNS(ns,'symbol'); sym.setAttribute('id','i-mapa'); sym.setAttribute('viewBox',`0 0 ${MAPA_MX.w} ${MAPA_MX.h}`);
  sym.innerHTML = Object.entries(MAPA_MX.edo).map(([k,d])=>`<path d="${d}" fill="${(REGIONES[REGION_DE_EDO[k]]||{color:'#9cbf5a'}).color}" stroke="#fffaf0" stroke-width="3"/>`).join('');
  sp.parentNode.appendChild(sym); })();

S = cargar();
render();
